### ISSUE TITLE
[poll] Namespace refactoring

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#101]
Let's open up a vote:

 👍 - if you want Relation_SQL to be moved into atk4\data\Relation, Join_SQL into \atk4\data\Join and so on.
 👎 - if you are indifferent and don't clearly see benefits of this proposal.

**Comment by romaninsh** [comment]
That also means that "Model_User" will be Model\User probably and any other underscores will be removed.

**Comment by DarkSide666** [comment]
I like removing underscores and putting classes in deeper physical folder structure, but I don't like that classes live in separate namespaces. So, I'm not sure should I vote Yes or No :)

**Comment by romaninsh** [comment]
I think it's the right way to go too. There might be incompatibility with ATK though, but  nothing major.

**Comment by romaninsh** [comment]
Due to changes in Agile Core we will prefer namespaces, so those classes should be moved eventually.

**Comment by abbadon1334** [comment]
all atk4\data was refactored and leaved a class with underscore for backward compatibility. this can be closed.
