### ISSUE TITLE
setLimit(1) not working

### ISSUE THREAD

**Issue by mkrecek234** [atk4/data#1010]
Steps to reproduce:
1. Select any model and add some conditions which result in multiple records. Optionally also setOrder.
2. Apply setLimit(1) to restrict to one record only
3. Then tryLoadOne()

I get this error: `Atk4\Data\Exception: Ambiguous conditions, more than one record can be loaded`
Code snippet:
```
$customermodel = new \Atk4\Data\Model\Customer($db);
$customermodel->addCondition(\Atk4\Data\Model\Scope::CreateOr(['phone', 'LIKE', '%'.$number.'%'], ['mobile', 'LIKE', '%'.$number.'%']));
$customermodel->setOrder(['id']);
$customermodel->setLimit(1);
$entity = $customermodel->tryLoadOne();
```

What should be expected:
If there was minimum one entity matching the conditions, $entity should contain that (first) one, otherwise $entity == null.

**Comment by mvorisek** [comment]
interesting finding, strictly taken it is a bug, as model modelled with max. 1 record cannot contain more than one record :)

I belive the `$customermodel->addCondition(...)` in the repro code is not even needed (and technically the `setOrder` neither, although any matching record will be picked)
