### ISSUE TITLE
Model_ not necessary for the Model

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#104]
Prefixing model with Model_ shouldn't be mandatory. Some people may want to place them inside a separate namespace.

```
class Client extends \atk4\data\Model {
}
```

I need to figure out a good way for this to work in a backwards-compatible way. Related to #101

**Comment by DarkSide666** [comment]
Currently there is only one place where `Model_` prefix is hard-coded in Agile Data.
It's in Model class, _hasRelation method.

**Comment by romaninsh** [comment]
Related: #152

**Comment by abbadon1334** [comment]
not an issue anymore
