### ISSUE TITLE
HasOneSql is not merging imported field seed properly

### ISSUE THREAD

**Issue by mkrecek234** [atk4/data#1046]
Steps to reproduce:
1. You have a model and addExpression which by nature is non-editable.
2. You for example relate to that model with a hasOne relation, and import that expression as a field

Error `TypeError: Atk4\Data\Field::isEditable(): Return value must be of type bool, array returned`
in Model:730

The issue is in line 734, as isEditable is not existing as a property for SqlExpressionField.

**Comment by mvorisek** [comment]
@mkrecek234 please do not add `MAJOR` to (every) bug, `MAJOR` is something conceptually wrong or with major impact on most users.

Also, please copy/screenshot full backtrace in case you want to refer to it. Refering to a line number without knowing the file is almost useless. The same for the exception message, as the reason might depend on a context which is shown in exceptions params (added by `Exception::addMoreInfo()`).

**Comment by mkrecek234** [comment]
![image](https://user-images.githubusercontent.com/28671486/182816395-02004805-19c3-4772-a068-ddbb5a394bbc.png)

**Comment by mvorisek** [comment]
> The issue is in line 734, as isEditable is not existing as a property for SqlExpressionField.

There is no `isEditable` property in atk4/data. There is only `Field::isEditable()` method, which by inheritance available in `SqlExpressionField`. Can you please post a minimalistic code to reproduce or is it possible to reproduce it on atk4/ui demos?

**Comment by mkrecek234** [comment]
Correct - it relates to the missing isEditable() property of SqlExpressionField. In Model::getFields() the following code is not compatible with SqlExpressionField:
``` if (
                    ($f === 'system' && $field->system)
                    || ($f === 'not system' && !$field->system)
                    || ($f === 'editable' && $field->isEditable())
                    || ($f === 'visible' && $field->isVisible())
                ) {
```
As I cannot create minimalistic code on demo today, here already the info to reproduce:

1. Add an expression to any model.
`$model->addExpression('expressionfield', ['expr' => "1"]);`

In a child model create a hasOne and import that expression:
`$childmodel->hasOne('model_id', ['model' => [Model::class]])->addFields(['expressionfield']);`

Then simple check it in a crud:
`$crud->setModel($childmodel);`

**Comment by mkrecek234** [comment]
I checked further, the issue is that `$this->ui['editable']`in [Field:457](https://github.com/atk4/data/blob/ac637ce4389eb34ce7e118008a7cc356a47587c0/src/Field.php#L457) returns an array which includes true and false, rather than just a boolean value.

**Comment by mvorisek** [comment]
Thank you for the code. I am looking into it.

> it relates to the missing isEditable() property of SqlExpressionField

really a property? I seached `->(is)?editable(?!\()`, no such property is accessed in the whole project

I belive the issue is caused by `ui['editable']` beiing an array - https://github.com/atk4/data/blob/0892a701f955b5c560bb3dd324645788bedd7594/src/Field.php#L457

**Comment by mkrecek234** [comment]
![image](https://user-images.githubusercontent.com/28671486/182820080-f4487de0-4979-419c-9d20-25266edd9d6a.png)

**Comment by mvorisek** [comment]
yes, doesn't it come from your code?

**Comment by mkrecek234** [comment]
No, I haven't touched anything there, just standard model definitions

**Comment by mvorisek** [comment]
issue is here: https://github.com/atk4/data/blob/0892a701f955b5c560bb3dd324645788bedd7594/src/Reference/HasOneSql.php#L87

`array_merge_recursive` is not merging the seed properly - https://3v4l.org/4Tgo8
