### ISSUE TITLE
Create standard field flags

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#105]
@DarkSide666: I guess we should have more field statuses or flags in Agile Data:

## Agile Data flags:

All the fields support that. Those flags will impact query building.

* `system` - this field is needed inside some Hook, always loaded and saved.
* `never_persist` - field does not exist in persistence. never loaded or saved.
* `readonly` - field value may not be changed. never saved. (Expressions are read-only)

## UI Flags

Setting those flags may affect UI layer in a general way, but will have no effect on Agile Data:

* `ui/editable` - display this field inside form. If unspecified !system is used.
* `ui/visible` - display this field inside grid. If unspecified !system is used.
* `ui/hidden` - never consider this field for UI.

Editable / Visible fields can be overwritten by 2nd parameter to setModel() method of Agile toolkit.

If any of the fields are "hidden" they should still be excluded from the UI.

## ACL Extension

It's possible to define a further rules on when fields can be defined, by whom etc. ACL extension would be looking after that.

* `acl/set` - override permission to set the field value through ->set(). Will not affect persistence.
* `acl/insert` - override permission to have the field dirty when adding new record.
* `acl/edit` - override permission to have this field dirty when editing.

------

Callbacks: Need ability to set callback instead of true/false value for all statuses mentioned above.

TODO: define a unified way how to verify flags, which can be used by UI layer to determine which fields must be displayed, etc.

**Comment by romaninsh** [comment]
fixed in #106

**Comment by romaninsh** [comment]
We need to make a comprehensive test-suite to verify the working of the flags.. Also we need to do something about ACLs.

**Comment by romaninsh** [comment]
fully fixed in #130

**Comment by DarkSide666** [comment]
except ACL flags, but ACL most likely will be separate extension out of the core anyway

**Comment by romaninsh** [comment]
Currently the only test that is skipped is the one that tests set/get callbacks. I removed hook trait from the fields, and wanted to have the hook inside the model instead. Would need to create a few tests, but that can be a separate PR.
