### ISSUE TITLE
Fix all typos

### ISSUE THREAD

**Issue by szepeviktor** [atk4/data#1104]
Hello @mvorisek! I've made a tool for you.
https://github.com/szepeviktor/typos-on-you
It finds typos in any repository.

Output for atk4/data
https://github.com/szepeviktor/typos-on-you/actions/runs/5371072403/jobs/9743586984
Output for atk4/ui
https://github.com/szepeviktor/typos-on-you/actions/runs/5371108915 - generated files should be ignored

Would you like to receive a PR fixing these?

**Comment by mvorisek** [comment]
Please review all atk4/core, atk4/data (this) and atk4/ui repos. At least the docs and php files.

**Comment by szepeviktor** [comment]
Done 🍏

**Comment by szepeviktor** [comment]
Please give me some work. (that satisfies my hunger for the _Joy of Work_)

**Comment by mvorisek** [comment]
Thank you for caring about our grammar. For more contributions, see atk4/data and atk4/ui issues.
