### ISSUE TITLE
Bad float/integer input is silently accepted

### ISSUE THREAD

**Issue by mkrecek234** [atk4/data#1139]
You have `float` or `integer` fields and have a standard edit form to edit those.
If you enter any text `hello` into those `float` or `integer` fields, Atk4/Ui will validate them as OK, and Atk4/Data will store them as if you had typed in `0`.

This is dangerous and wrong.

Any number field should not accept wrong text, otherwise type validation does not make any sense.

Expected behaviour:
Any number field should throw a ValidationException if it cannot correctly interprete the input value. Interpreting this as `0` if the user has another intention is dangerous.

**Comment by mvorisek** [comment]
as discussed in the chat, this is not a bug as such behaviour is defined by the underlaying official DBAL IntegerType, FloatType classes

**Comment by mkrecek234** [comment]
@mvorisek This is clearly a bug from a user perspective. Just because a referenced DBAL type might do this, this does not mean that users intended to enter a `0` value if they entered random text. This turns form validation upside down. What age are you? Answer: `lksjdf`. 

Ahhh, you are 0 years old! 😀

**Comment by mvorisek** [comment]
I agree. The bug/FR classification is done like this - bug: was supported, now broken, FR - everything else (and `MAJOR` - major new feature)

**Comment by mkrecek234** [comment]
I'd say: A bug is a bug - if it was supported or was working before does not matter. Even if your car never worked coming out of factory and always stopped driving after 2min, then it obviously has a bug. If it was ever driving longer than 2mins does not matter.

**Comment by mvorisek** [comment]
we understand each well, this is a matter of classification only, but as long as the car was expected to run for much longer, than the example you posted is a bug/defect, here, the throwing was simply not implemented in atk4/data, slightly intended, as my projects use stricter/custom DBAL types which detect the problem :)

in computer science, in upper layers, we usually do not want to detect problems that should be detected in lower layers

**Comment by mvorisek** [comment]
Also unexpected value is silently accepted by `boolean` DBAL type, like `off` (parsed to true).

**Comment by mvorisek** [comment]
> Atk4/Ui will validate them as OK, and Atk4/Data will store them as if you had typed in `0`.

The problem is in atk4/data typecasting. Field normalize handles this/throws, but typecasting does not.

This problem is present only with the default DBAL types. They should throw when typecasting from/to DB.

**Comment by mvorisek** [comment]
@mkrecek234 can you please check if it is fixed everywhere?

**Comment by mkrecek234** [comment]
@mvorisek Will do asap

**Comment by mkrecek234** [comment]
@mvorisek Looks good to me 👍
