### ISSUE TITLE
How to schema->upgrade() ?

### ISSUE THREAD

**Issue by Vladzimir** [atk4/data#1166]
This code not work!
```
$m->onHook(Model::HOOK_ROLLBACK, function (Model $m, \Throwable $exception) {
    if ($exception instanceof SqlException) {
        $m->schema->upgrade();
        $m->breakHook(false); // exception will not be thrown
    }
});
```

**Comment by mvorisek** [comment]
TBH, I do not know what you mean, what is `$m->schema`, what is `schema->upgrade()`?

Github issues are not free support. Fell free to discuss your usecase on our Discord forum though.

**Comment by Vladzimir** [comment]
https://atk4-data.readthedocs.io/en/develop/hooks.html?highlight=upgrade#onrollback-hook 
Upgrade schema:

**Comment by mvorisek** [comment]
To upgrade a schema, create Migrator, setup it like you would for create, and then use Doctrine DBAL directly to apply the `$migrator->table`. Help with docs welcomed.
