### ISSUE TITLE
Migrator::create() adds Fields from Join to Model table

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/data#1226]
Some Code from my application (Tour Model):
```php
        $ttJoin = $this->leftJoin('tour_type', ['masterField' => 'tour_type_id']);

        $ttJoin->addField('activity_id', ['system' => true]);
```
When using `Migrator::create()` to create a table for this Model, the field `activity_id` is added.

I will provide a minimal test to reproduce.

**Comment by mvorisek** [comment]
Please provide repro and explain why you do not expect the field to be created in the DB, isn't is required for SQL join?

**Comment by PhilippGrashoff** [comment]
Hi, repro will come, very busy these days.
ModelA has a left join on ModelB. However, the fields imported by the join are created in the ModelA table. If they should be created at all by Migrator (I do not think they should), they should be created in ModelB table.

**Comment by PhilippGrashoff** [comment]
Hi, I added a failing test to MigratorTest to demonstrate the problem: https://github.com/atk4/data/pull/1227

**Comment by mvorisek** [comment]
Thank you for the repro. Please make all CI checks passing there.

**Comment by PhilippGrashoff** [comment]
At the moment, I only added a failing test for the problem described here. Could you hint me to a good entry point to start debugging? I will complete the PR then.

**Comment by mvorisek** [comment]
The join is created in https://github.com/atk4/data/blob/5.2.0/src/Model/JoinsTrait.php#L55 and the field in https://github.com/atk4/data/blob/5.2.0/src/Model/Join.php#L318 . In Migrator, you should check `Field::hasJoin()` and `Field::getJoin()` (https://github.com/atk4/data/blob/5.2.0/src/Model/JoinLinkTrait.php#L11).
