### ISSUE TITLE
Add validation for Enum

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#125]
must be in array of possible options. Otherwise what's the point defining it.

**Comment by DarkSide666** [comment]
That's task for Validator class I guess, right?

**Comment by romaninsh** [comment]
Fixed in #130.

**Comment by romaninsh** [comment]
I've thought about if it should be validator or not. Basically - the default type-casting should ensure that persistence (SQL) can physically store the data. For example when you store "boolean" it converts it to "INT" because that will prevent SQL exception. Trying to save NULL into Mandatory fields will prevent "not null" from catching this problem.

Enum property often means that database has also used "ENUM" definition and storing value outside of allowed ones will be a problem. So the enum validation is essential.

Validator can do other things, but ensuring that "enum" is one of the allowed values is essential to the core data handling.

**Comment by DarkSide666** [comment]
I agree

**Comment by DarkSide666** [comment]
fixed
