### ISSUE TITLE
better implementation for `fmt` and currency for money.

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#131]
Currently, is not fully implemented.

**Comment by romaninsh** [comment]
With  #144 implementing fmt/currency is much simpler. Documentation even refers to Advanced section where 'Field_Currency' could be implemented. 

But the destination article is missing. Also custom formats has mention in the documentation, but does not seem to reflect in the code and does not have any test-scripts.

**Comment by DarkSide666** [comment]
related discussion: https://github.com/atk4/data/issues/147

**Comment by romaninsh** [comment]
After much thought I decided to drop the 'fmt' entirely and leave money implementation as-is. Let's focus on releasing 1.1 now.
