### ISSUE TITLE
Provide test-case for casting empty strings into null values

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#132]
Sometimes we do not want to store empty strings in the SQL database, and instead we want to convert them into NULL values. 

Need a test-script for a good implementation and maybe an advanced topic in the doc.

**Comment by DarkSide666** [comment]
... and this is not only about casting string into null values.
Need some examples how developer can easily customize normalization as such - per field, per field type, per model, with overwriting original normalization or as additional normalization etc.

**Comment by mvorisek** [comment]
closing in favor of https://github.com/atk4/data/issues/577
