### ISSUE TITLE
Reference_One->addTitle() changes

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#137]
* addTitle() should return new Expression field not Reference_One instance;
* addTitle() should have ability to pass $defaults to expression field;
* ~~addTitle() shouldn't set read_only=false, expressions should always be read_only=true. And no need for never_save=true here if we already set read_only=true;~~
* addTitle() should by default advice UI to not show title field in forms as editable field. This can be overwritten by passing $defaults in addTitle() method.

**Comment by romaninsh** [comment]
I disagree with the point 1.

    $this->hasMany(..)->addTitle()->addFields()..

returning the title itself does not give us anything. We can suggest user to look into addField() if they want to do something fancy.

**Comment by romaninsh** [comment]
I recommend adding: `withTitle()` same format as `addTitle` but would return Reference the way how addTitle works now.

**Comment by DarkSide666** [comment]
agree, implemented: https://github.com/atk4/data/pull/139/commits/ed03e3bc62090035fcc6d48431d76bdefce2d1d0
