### ISSUE TITLE
Check out which Traits we actually need and why

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#138]
- remove HookTrait from Field class (not used)
- add InitializerTrait in Field class (not sure about this)
- maybe create Trait for __construct($defaults) to take care of $defaults in unified way and not duplicate this code in almost all classes?

**Comment by romaninsh** [comment]
Move the Field_SQL methods into trait also, so that 3rd party extensions have easier time implementing those.

**Comment by romaninsh** [comment]
this was implemented differently, and no longer relevant.
