### ISSUE TITLE
Apply PSR standards for library interoperability

### ISSUE THREAD

**Issue by devsdmf** [atk4/data#14]
I'd like to see the library into the PSR standards, it grants better project acceptation and framework interoperability.

Reference: http://www.php-fig.org

**Comment by romaninsh** [comment]
That's certainly in the plans :)

**Comment by romaninsh** [comment]
@devsdmf I'll be moving this into a later milestone. We need to release 0.3 shortly and make sure library is in a good working condition and can be used in our external projects. Then we can start cleaning it up.

**Comment by romaninsh** [comment]
We are now using StyleCI which makes sure all the code is sparkling !
