### ISSUE TITLE
Date field normalization issues

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#140]
**Situation:**
* DB have field with type `date`
* Model have respective field with type `date`
* TimeZone of application is set to `Europe/Riga`

**Reproduce issue:**
* Open app form with DatePicker, choose date value, let's say 2016-09-13, submit form
* There is small, partial fix for Atk4 forms to workwith model field value with type DateTime (https://github.com/atk4/atk4/commit/755e0d39cc6c4100a3232b155263bf93a9311346)
* So, models `Persistence_SQL->typecastSaveToPersistence` receives DateTime object, changes timezone to UTC and get `2016-09-12 21:00:00` as result.
* Model saves this in DB and only date part of datetime is stored, because this is date field. As result in DB we have `2016-09-12`.
* When we  try to load date back from DB with Agile Data, we receive DateTime object with UTC timezone and value `2016-09-12 00:00:00`.
* Later one app can try to set its timezone, but that will not help (resulting in 2016-09-12 03:00:00) because in DB we automatically trimmed time part of datetime.

At first it looks that it's expected behavior, but ... in case field type is date not datetime - this produces hard to track and understand bugs in app.
For example, in app I set invoice date to 2016-09-13, save, reload and my invoice shows up as 2016-09-12. I can even save it again and it will reload as 2016-09-11 and so on :)

**Comment by romaninsh** [comment]
BTW - what do you think about the following workflow:

 - [ ] Create PR for this ticket
 - [ ] Add a test-script that reproduces the above issue and fails.
 - [ ] Leave it for someone to fix
 - [ ] When fixed, merge.

**Comment by DarkSide666** [comment]
Should be fixed in https://github.com/atk4/data/pull/130.

**Comment by DarkSide666** [comment]
fixed
