### ISSUE TITLE
Application Error: You are trying to link tables on non-id fields. This is not implemented yet

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#148]
This is essential for super/sub-typing.
- super-type: table List (id, name, type)
- sub-type: table Vat_rate(list_id, percent, is_default). This table have list_id as primary key, but without auto-increment and it is directly linked with List.id

---

Actually I got it working.

```
$j1 = $list->join('vat_rate.list_id', 'id'); // this throws exception, see above
$j2 = $list->join('vat_rate.list_id'); // this works
```

But this is strange behavior anyway :)

**Comment by NotAProfessionalDeveloper** [comment]
Hmm, not sure what to make of this. I am getting the same in Agile Toolkit 1.7. However milestone is set to 1.2.
If I can't properly join my data this product is of no use to me.

**Comment by DarkSide666** [comment]
These milestones are a long past. It's v2.0 out already :)

And this is no issue anymore anyway. You can join tables or you can use references, but in this exact example I think join is more proper.

**Comment by NotAProfessionalDeveloper** [comment]
Oh, is there a toolkit 2.x? Actually it's quite confusing. V4 was first? Then v1, now v2, but only certain components?

**Comment by DarkSide666** [comment]
At first years ago toolkit was one framework which included everything. It's `atk4/atk4` repository.

Then we decided to move on and refactored it from scratch and split it in mostly independent parts to be able to use them even without other parts. For example, we can now use `atk4/data` with Laravel for UI etc. And versioning of these separate parts started from zero again because these were new repositories.
Now we have `atk4/core`, `atk4/dsql`, `atk4/data`, `atk4/ui` and bunch of other components which works nicely together, but also can be used separately. Toolkit (`atk4/atk4`) is deprecated and shouldn't be used for new projects.

**Comment by NotAProfessionalDeveloper** [comment]
Oh, but it's prominently featured for download when you go to agiletoolkit.org.

**Comment by DarkSide666** [comment]
That's a crap what you can download from agiletoolkit.org as 1.7.1 :)

If you're starting new project, then you should use 2.x versions and install and use composer.
That's how it works the best. Of course you will need internet connectivity to get newest versions from github.
