### ISSUE TITLE
Need setDefaults or similar method for all classes

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#150]
Currently we only have `setDefaults()` method for Model class, but it can be useful to have such method (or similar) for all classes. Actually this can be defined as a Trait and used everywhere. Maybe even defined in atk/core?

For example, currently I have to do like this to change multiple objects properties after it is defined:

```
$field = $m->getElement('ref_no');
$field->mandatory = true;
$field->ui['editable'] = false;
$field->...
...
```

It would be much more elegant if I could do like this:

```
$m->getElement('ref_no')->setProperties([
    'mandatory' => true,
    'ui' => ['editable' => false],
    ...
]);
```

Also all Agile Data constructors could use this method for consistency and to avoid code duplication.

**Comment by mvorisek** [comment]
Any class that has DIContainerTrait already support it - see https://github.com/atk4/core/blob/503ed2ff35865ca8b5499ecb61c95a6257b95621/src/DIContainerTrait.php#L50
