### ISSUE TITLE
Allow Persistence to hold "model prefix" property.

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#152]
Currently factory has "Model_" prefix hardcoded for models defined through string:

```
$user->hasMany('Order');  // Model_Order
```

Some users may prefer to use namespace for their models. Currently they can do this:

```
$user->hasMany(new Order());
```

However it should also be possible to define default model prefix inside persistence through a property. 

```
$db->model_prefix='bizlogic\';
$db->add('Order');  // bizlogic\Order class
```

**Comment by DarkSide666** [comment]
In Agile Data only in Model->_hasReference we have this: https://github.com/atk4/data/blob/develop/src/Model.php#L1474

But we should treat this better in toolkit too to pick up Agile Data persistence->model_prefix instead of hard-coded 'Model_'.

**Comment by romaninsh** [comment]
What about persistence :: add

**Comment by DarkSide666** [comment]
Persistence::add use factory and pass the same class name which it receives from outside.
So `$persistence::add('Invoice')` should work out-of-the box already.

**Comment by romaninsh** [comment]
Affected by #261 , which changes "Model_" to "Model\\"

**Comment by abbadon1334** [comment]
not an issue anymore
