### ISSUE TITLE
Model Mutability

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#153]
While model is being initialized it can have various conditions added. Calling `addCondition` will modify the objects that is being currently initialized.

Once init is complete, we can say that the model has entered it's finalised state. 

Agile Data allow to add more conditions in-line:

```
$m = new User($db);
$m->addCondition('happy', true);
```

However this can lead to conditions where active record does not actually match the condition. 

Some user have suggested that we introduce "immutability" so that once model conditions are set, adding more conditions would cause model to be cloned:

```
$m = new User($db);
$happy_user = $m->addCondition('happy', true);

$m->load($unhappy_user_id); // not affected by the condition
```

However, with the number of field declarations, this can be quite cpu-consuming especially if multiple extra fields need to be added. 

Ideas are welcome!

**Comment by DarkSide666** [comment]
This will definitely require much more cpu and ram resources. I don't think its good solution.
Also it will be hard to understand which model is which. For example,
```
$m = new User($db);
$happy_user = $m->addCondition('happy', true);
$male_user = $happy_user->addCondition('male', true);
$over_18 = $male_user->addCodition('age', '>', 18);
...
```
In this case we already will have 4 models instead of one and also a lot of additional variables are needed which will lead to even more confusion.

**Comment by skondakov** [comment]
I also do not like the idea of mutability. It seems very CPU & memory consuming. IMO if active record does not match the set changes, an exception should be thrown.
