### ISSUE TITLE
Add support for nested models

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#183]
We need a proxy persistence. For one it will be really useful for Forms. Here is how I think it should work.
1. You create blank model and associate it with Proxy persistence.
2. You can add multiple models through a special method, and specify which fields you want to import.
3. Importing fields will copy all the properties
4. When you execute save() then $data[] is simply copied into relevant models then save() is executed on those models.
5. If multiple linked models exist within same persistence, we group them into atomic() operation.
6. There should be a way on how to link models. E.g. create "User" and "User_Contact", but the second should receive user_id value.
7. Proxy model can be saved into session easily if we want for multi-record operations.
8. Proxy can be used recursively (just a test no practical use).
9. Extra hooks.
10. Fields can be imported in a different order.
11. Support groups.
12. Support iterating. One model will be main, but other model will be intelligently pre-fetched and results connected.
13. Support grouping/aggregation. (not sure how yet)
14. Some support for switching nested model persistences (e.g. load from cache, but update back to API)
15. Support for order and limit

Proxy will be used extensively by Views (in Agile/UI). Adding field into Form will add it into proxy. Using setModel() will import bunch of fields into proxy. The same goes for Grid. 

Proxies will quite often use a custom Field class. Proxy can also type-cast into formats that are designed for presenting, e.g. format date using locale, etc.

**Comment by mvorisek** [comment]
I think the correct approach is to support any Model as another Model source/table. Ideally RW if not grouped.

**Comment by mvorisek** [comment]
implemented in https://github.com/atk4/data/pull/946
