### ISSUE TITLE
Typecast use of 'actual' clashes with persistence->update()

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#186]
It looks like fields are converted to actual twice. Looking into persistenceSQL, method update:

```
$data = $this->typecastSaveRow($m, $data);
```

This will also replace certain keys with their 'actual' values, which is probably the right thing to do. But right after we do this:

```
foreach ($data as $field => $value) {
    $f = $m->getElement($field);
```

Since we just converted to plain values, then there wouldn't be an element in here. As a result "plain" values totally fail on update().

**Comment by DarkSide666** [comment]
I think this is no more the case and this issue can be closed.
Code have changed long time ago.
