### ISSUE TITLE
Agile Toolkit Form does not respect caption.

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#196]
Grid does, Form doesn't.

**Comment by DarkSide666** [comment]
Actually it's opposite. Form is correct, but grid controller had bug.
Usage should be `$field->ui['caption']` instead of `$field->caption` because caption is only important for UI layer and all UI layer related properties we put in $field->ui array.

**Comment by DarkSide666** [comment]
fixed in toolkit ADGrid controller
