### ISSUE TITLE
looks like misspelled ->table

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#212]
This line possibly accesses non-existent property.

https://github.com/atk4/data/blob/develop/src/Join.php#L328

**Comment by DarkSide666** [comment]
Probably there should be `$model->table.'_id'`

**Comment by DarkSide666** [comment]
https://github.com/atk4/data/blob/develop/src/Join.php#L342

**Comment by romaninsh** [comment]
not sure myself anymore :)
