### ISSUE TITLE
Passing defaults to hasOne (SQL)

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#216]
```
$this->j_head->hasOne('vat_period_id', ['smbo/VatPeriod', 'caption'=>'VAT Period'])->addTitle();
var_dump($this->getElement('vat_period_id')->caption);
```

The above code outputs NULL but caption property should have been set for the field. This issue needs a proper test and fix.

**Comment by romaninsh** [comment]
there are several other methods that needs to be looked at, btw.

**Comment by romaninsh** [comment]
This might be useful: http://agile-ui.readthedocs.io/en/latest/core.html#seed

**Comment by DarkSide666** [comment]
yeah, I read about seeds yesterday and now I think I understand UI constructor parameters at last ;)

**Comment by romaninsh** [comment]
not sure if relevant, but we introduced 'hasTitle'
