### ISSUE TITLE
addTitle() doesn't work for fields without _id suffix

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#220]
```
$payment->getRef('contractor_to')->addTitle()
```
throws
```
Element with requested name already exists
Additional information:
element: 
arg2: ["contractor_to"]
```
that's because of;
```
        $field = str_replace('_id', '', $this->link);
        $ex = $this->owner->addExpression($field, array_merge_recursive(
```
in Reference_SQL_One->addTitle() https://github.com/atk4/data/blob/develop/src/Reference_SQL_One.php#L145

it tries to create field with exactly the same name (because it doesn't have _id suffix) and of course fails.

*Possible solution:*
if there is `_id` suffix, then do like now. if there is no _id suffix, then add some additional suffix like `_name` after $this->link.

**Comment by romaninsh** [comment]
Temporary workaround - use addField()
