### ISSUE TITLE
Refactor to use DI Container

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#228]
Agile core finally implements DI Container Trait: https://github.com/atk4/core/pull/47

Refactor UI constructors to use this trait where possible

See similar bug for UI: https://github.com/atk4/ui/issues/129.

**Comment by DarkSide666** [comment]
related https://github.com/atk4/data/issues/249

**Comment by romaninsh** [comment]
hopefully can be fixed in #314

**Comment by romaninsh** [comment]
Done in https://github.com/atk4/data/blob/develop/src/Field.php#L7
