### ISSUE TITLE
Migrate Model AutoCreator to Agile Data

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#251]
When ATK was a monolitic framework, a [very nice add-on existed for keeping database schema synced up with the model](https://github.com/atk4/atk4-addons/tree/master/dynamic_model).

Agile Data is a bit more diverse supporting SQL and NoSQL, but it could still use a nice add-on for "syncing" your database schema to your model. Original addon was able to catch database exceptions and alter DB transparently, but that's not very viable with Agile Data.

 - Need to be able to pull out list of fields from specified Model
 - Must recognize relations (if they are going to same persistence)
 - Should handle logic with "id" fields and no-id.
 - Must preserve existing structure and data.

The create actions should be expressed through https://github.com/atk4/schema. This should allow various options of "storing migration steps as PHP" or "storing migration as SQL" or applying migrations immediately.

**Comment by DarkSide666** [comment]
@romans This is implemented in https://github.com/atk4/schema and I think there is no reason for keeping this issue in atk4/data open.

**Comment by romaninsh** [comment]
Agreed. Old ticket. Closing.
