### ISSUE TITLE
Do you plan to respect semver ?

### ISSUE THREAD

**Issue by syrm** [atk4/data#268]
-@romans----------
We should describe our general policy towards "backward compatibility" breaking changes and make sure reviewers are familiar with it.

For example - if public property of the class is changed, would that require major version change for the library?

-was-----------
Hello,

Do you plan to respect semver ?

**Comment by romaninsh** [comment]
yes (details in chat)

**Comment by romaninsh** [comment]
Re-opening with amended description.

**Comment by romaninsh** [comment]
bc-breaks are now used when changes are potentially breaking and this applies to major commits.
