### ISSUE TITLE
Tests of CSV persistence fail on Windows

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#271]
Tests of CSV persistence fail on Windows.

```
1) atk4\data\tests\CSVTest::testLoadAny
unlink(atk-test.csv): Resource temporarily unavailable

C:\wamp64\www\git\data\tests\CSVTest.php:28
C:\wamp64\www\git\data\tests\TestCase.php:10
C:\Users\Admin\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:186
C:\Users\Admin\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:116

2) atk4\data\tests\CSVTest::testLoadAnyException
unlink(atk-test.csv): Resource temporarily unavailable

C:\wamp64\www\git\data\tests\CSVTest.php:28
C:\wamp64\www\git\data\tests\TestCase.php:10
C:\Users\Admin\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:186
C:\Users\Admin\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:116

3) atk4\data\tests\CSVTest::testPersistenceCopy
unlink(atk-test.csv): Resource temporarily unavailable

C:\wamp64\www\git\data\tests\CSVTest.php:28
C:\wamp64\www\git\data\tests\TestCase.php:10
C:\Users\Admin\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:186
C:\Users\Admin\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:116
```

As far as I can tell it can't delete file because it's still open (accessed by another process) and that happens because Persistence_CSV closes file only on __destroy event and most likely destroy is not happening unless whole tests are finished.
Using tearDownAfterClass() instead don't help too. Using unset($p) in tests also don't help.

**Comment by romaninsh** [comment]
I don't have Windows computer to test, so if someone can help would appreciate it.

**Comment by DarkSide666** [comment]
Workaround committed here: https://github.com/atk4/data/commit/3f434140ad38956ec2de9dda2199c0e9c64e8f5a

**Comment by romaninsh** [comment]
does it actually delete the file ?

**Comment by DarkSide666** [comment]
No it does not. Workaround is to avoid exception and failing tests.

**Comment by romaninsh** [comment]
ok, fine lets close this now. Probably you should also add link to this issue in the code, because someone who reads it can go "WTF??".

**Comment by DarkSide666** [comment]
done
