### ISSUE TITLE
After latest composer update, warning is thrown in Persistence_SQL->initQueryFields()

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/data#274]
After the latest update yesterday, I get a lot of Warnings about a invalid argument for foreach:
`<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/html/TourManagement/vendor/atk4/data/src/Persistence_SQL.php</b> on line <b>240</b><br />`

Comment says that the function initQueryFields parameter 3 is either an array (of fields) or null:
```
 /**
     * Adds model fields in Query.
     *
     * @param Model            $m
     * @param \atk4\dsql\Query $q
     * @param array|null       $fields
     */
```
If only an array or null are valid values for $fields, the following check could be changed from:
       ` if ($fields) {`
to
        `if (is_array($fields)) {`

This makes my warnings disappear.
The warning is caused by a lot of select functions like Model->tryLoad() or Model->export().

Best regards
Philipp

**Comment by DarkSide666** [comment]
That's try, but also maybe this linehttps://github.com/atk4/data/blob/develop/src/Persistence_SQL.php#L541

should use `$args` not `$args[0]`

**Comment by DarkSide666** [comment]
fix PR created https://github.com/atk4/data/pull/275
