### ISSUE TITLE
Oracle dates not working properly

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#279]
When date field is added like this:

``` php
$this->addField('DAT_BEZ_REG',['type'=>'date','caption'=>'Datums bez reģ.']);
```

and field in the table declared as:

``` sql
alter table x add 'DAT_BEZ_REG' date (????????);
```

and UI code is:

``` php
$app->add('CRUD')->setModel('TestModel');
```

Getting error:

Fatal Error
atk4\data\Exception: Incorrectly formatted date/time
Exception Parameters
format: "+!Y-m-d"
value: "2007.07.12"
field: atk4\data\Field_SQL (_DAT_BEZ_REG)

<img width="435" alt="screen shot 2018-01-18 at 16 44 44" src="https://user-images.githubusercontent.com/453929/35109656-e6ceef38-fc6e-11e7-8917-852fb1bd0d53.png">

**Comment by DarkSide666** [comment]
Can reproduce:
```
format: "+!Y-m-d"
value: "21-JAN-18"
field: atk4\data\Field_SQL (_PLACED)
```
In my case value is in even different format.
