### ISSUE TITLE
Problem with oracle insert

### ISSUE THREAD

**Issue by andrejsdr** [atk4/data#280]
SQLSTATE[IM001]: Driver does not support this function: driver does not support lastInsertId()

**Comment by romaninsh** [comment]
Related: https://stackoverflow.com/questions/34811283/retrieve-oracle-last-inserted-identity

**Comment by DarkSide666** [comment]
This is bad :( We can't be sure that there will always be related Sequence.
Anyway I will think about this, just can't promise that that will be today.

**Comment by romaninsh** [comment]
that's why user would have to specify it.

**Comment by andrejsdr** [comment]
I got the KODS with beforeSave  hook

 $this->addHook('beforeSave', function($m){
            // check if insert or update
            if (!$m->loaded()) {
                $m['KODS'] = $m->expr('select ligumi_seq.nextval from dual')->getOne();
            }
  });        

Now insert is correct but I have
SQLSTATE[IM001]: Driver does not support this function: driver does not support lastInsertId()

**Comment by DarkSide666** [comment]
should be fixed in https://github.com/atk4/data/pull/285
