### ISSUE TITLE
action(count) doesn't take setLimit into account

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#281]
$model->action(count) doesn't take setLimit into account.

```
$m->setLimit(100);
echo $m->action('count')->getOne();
// count here will not be 100, but count of all model rows.
// it takes model conditions into account, but not limit.
```

There are pros and cons of this.
 - On one hand it's ok to calculate count without taking limit into account, because limit is not exactly condition, it's kind of "lazy-load" condition.
 - On other hand it's a bit confusing that if you set limit to 10 rows, but it still says that there are 9999 rows (see example above).

**Comment by romaninsh** [comment]
yes, that is correct action. 

Limit is applied after aggregation. You can remove limit from the query for the 'count' action., to keep query clean.

**Comment by DarkSide666** [comment]
So you say it's ok as it is now and this issue should be closed ?

**Comment by romaninsh** [comment]
yes, kinda.
