### ISSUE TITLE
Oracle: addCondition(field, null) throws exception

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#283]
WHERE condition with NULL value throws exception:
```
Exception: SQLSTATE[HY000]: General error: 908 OCIStmtExecute: ORA-00908: missing NULL keyword
 (ext\pdo_oci\oci_statement.c:159)
```

Generated prepared query is correct. It looks that something goes wrong in Oracle with PDO::PARAM_NULL setting in prepared query and query doesn't inject NULL value where it should be.

Tracked so far:
```
$s = $c->prepare('SELECT * FROM FAKER_PK WHERE GEN_CODE IS NULL');
```
is OK

```
$s = $c->prepare('SELECT * FROM FAKER_PK WHERE GEN_CODE IS :a');
$s->bindValue(':a', null, \PDO::PARAM_NULL);
```
throws exception

**Comment by romaninsh** [comment]
Could it be this: https://stackoverflow.com/a/1391801/204819

use `\PDO::PARAM_INT` instead of `\PDO::PARAM_NULL`

**Comment by mvorisek** [comment]
I fixed this, we do not bind null anymore, we render simply `NULL` into the SQL, issue was also with MSSQL
