### ISSUE TITLE
add travis testing for postgresql

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#288]
Now that DSQL supports PostgreSQL and #287 adds "pgsql://" as a recognized connection string, we should add support into travis.ci and run everything on postgresql.

The approach should be quite similar to this:

https://github.com/atk4/dsql/commit/c8d1b403998a919ba3a11465f5f7e22bd00ca388

although there may be some hiccups.

**Comment by gartner** [comment]
Lots of hiccups :-/ 
The tests are written for sqlite (I think) and some of them fail on mysql because the use of " to quote identifiers. Others fails, because they are compared to a string with " for quotes, but on mysql the resulting query is using ` ...

**Comment by romaninsh** [comment]
we can roll with it, simply by ignoring non-functional tests.
