### ISSUE TITLE
Easier access to title of a current record

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#289]
When we talk about columns, then we have title_column.

To access it reliably you would need something like this:

``` php
$title = ($m->hasElement($m->title_field) && $m->getElement($m->title_field) instanceof \atk4\data\FIeld) ? $m[$m->title_field] : $m->id;
```

It would be great if we could simply call:

``` php
$title = $m->getTitle()
```

**Comment by DarkSide666** [comment]
no, not `getTitle()`, but more likely `getRowTitle()`
