### ISSUE TITLE
DSN without password

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#298]
I think DNS without password should be legal:

```
mysql://root@localhost/db
```

but currently it throws warning here: https://github.com/atk4/data/blob/develop/src/Persistence.php#L40

``` log
5) atk4\schema\tests\ModelTest::testMigrateTable
Undefined index: pass
/home/travis/build/atk4/schema/vendor/atk4/data/src/Persistence.php:40
/home/travis/build/atk4/schema/src/PHPUnit_SchemaTestCase.php:24
/home/travis/build/atk4/schema/vendor/atk4/core/src/PHPUnit_AgileTestCase.php:10
/home/travis/build/atk4/schema/src/PHPUnit_SchemaTestCase.php:148
```

**Comment by DarkSide666** [comment]
Romans:

> Imants while you are at it, can you make somehow possible to detect inside Persistence what database type it is? e.g. $persistence_sql->sql_vendor ?
