### ISSUE TITLE
Model with properties: when iterating over several loaded Items, changes to property are done on all Items

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/data#318]
Hi there,

I think some Code explains it best:

1) A simple Model with a property $some_property:
```

<?php
namespace Pmg;

class PropertyIterationBug extends \atk4\data\Model {

	public $table = 'test';
	public $someProperty = [];
	
	function init() {
		parent::init();

		$this->addFields([
			['name', 'type'=>'string',  'caption' => 'Name'],
		]);
    }
}
```

2) In my test DB table, there are 4 entries to show you whats happening.
Now lets have a script iterate these 4 objects and do something with the property:
```

<?php
//Load Main App
require 'config.php';
$app = new \Pmg\TourManagement();

$test = new \Pmg\PropertyIterationBug($app->db);
$test->tryLoadAny();
if($test->loaded()) {
	$i = 1;
	foreach($test as $t) {
		$t->someProperty[] = $i;
		$i++;
		var_dump($t->someProperty);
	}
}
?>
```

Expected output? First object should get "1" as array element, second one should get "2" etc.
**Instead, all the changes to objects iterated prior to the current one are performed on the current one.**
So the fourth object iterated has the array values "1", "2", "3" and "4", instead of just "4". (I know its Integers, not Strings, " are for text readabilty).
Have a look at the var_dump output:

```
array(1) {
  [0]=>
  int(1)
}
array(2) {
  [0]=>
  int(1)
  [1]=>
  int(2)
}
array(3) {
  [0]=>
  int(1)
  [1]=>
  int(2)
  [2]=>
  int(3)
}
array(4) {
  [0]=>
  int(1)
  [1]=>
  int(2)
  [2]=>
  int(3)
  [3]=>
  int(4)
}
```

For reproducing quickly, you can download these two files and a simple SQL from http://www.spame.de/property_iteration_bug.zip

p.s: I just updated to the newest atk versions.

**Comment by PhilippGrashoff** [comment]
Here's a second example, included in Zip as well:
```

<?php
namespace Pmg;

class PropertyIterationBugTwo extends \atk4\data\Model {

	public $table = 'test';
	public $true_or_false = false;
	
	function init() {
		parent::init();

		$this->addFields([
			['name', 			'type'=>'string',  'caption' => 'Name'],
		]);
    }
}

```

And iterating again:

```
$test = new \Pmg\PropertyIterationBugTwo($app->db);
$test->tryLoadAny();
if($test->loaded()) {
	$i = 1;
	foreach($test as $t) {
		if($i === 1) {
			$t->true_or_false = true;
		}
		$i++;
		var_dump($t->true_or_false);
	}
}
```

What would we expect? Only the first iterated object has true_or_false set to true, the others should remain false. Bu they don't, this is the output:

```
bool(true)
bool(true)
bool(true)
bool(true)
```

**Comment by romaninsh** [comment]
yes iterating re-uses the same object. Model is an expensive object we can't create it for every row.

**Comment by PhilippGrashoff** [comment]
Its written in the docs actually, didn't properly RTFM:
http://agile-data.readthedocs.io/en/develop/results.html#iterate-through-model-data

Perhaps some addition to docs would be nice, like a warning that using properties causes the behaviour mentioned here.

**Comment by PhilippGrashoff** [comment]
And the way to make properties work with iterations is to set the properties to their initial value in an afterLoad hook in Model->init():

 ```
$this->addHook('afterLoad', function($m) {
			$m->notifications = [];
			$m->notifications_loaded = false;
		});
```

**Comment by DarkSide666** [comment]
Also i don't see the point why you need these two lines:
```
$test->tryLoadAny();
if($test->loaded()) {
```
Why not just loop? If there will be no records, then it will simply skip loop.

**Comment by PhilippGrashoff** [comment]
Had this in chat today... I am learning :) Produced some PHP warnings by doing something I thought was directly looping, but it was not.
