### ISSUE TITLE
Documentation atk4/data not meet atk/data-primer repository

### ISSUE THREAD

**Issue by Jmos** [atk4/data#328]
table names not same in documentation (expl. "contact_info' vs repository 'acct_contact_info')

**Comment by DarkSide666** [comment]
It's in quickstart.rst of Agile Data and data-primer.sql of Agile Data-primer.

Data-primer is quite outdated and in primer readme it's written that you have to import /docs/primer.sql file not /data-primer.sql.

**Comment by Jmos** [comment]
Thanx a lot but i solved other way

**Comment by romaninsh** [comment]
@Jmos - can you submit PR with the correct table name? That would be very helpful!

**Comment by Jmos** [comment]
I don't remember but i corrected in my example it was for learning  practice and the test files had been deleted.
