### ISSUE TITLE
Grid->addQuickSearch() + Field_Callback

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#329]
It seems that Grid->addQuickSearch() method does not work will Field_Callback.

I have the following model:

    class Country extends \AppAtk4\MyModel {
        public $title_field = 'calc_title';
        
        public function init() {
            parent::init();
            $this->addField('iso_code', ['type' => 'string', 'required' => true]); // ISO 3166-1 alpha-2
            $this->addField('name', ['type' => 'string', 'required' => true]);
            
            $this->addExpression('calc_title', ['CONCAT([iso_code], \' - \', [name])', 'type' => 'string', 'read_only' => true, 'ui' => ['visible' => false]]);
        }
    }

And Grid with search input inicialized by this code:

        $crud->setModel($model);
        
        // add quick search
        $searchFields = [];
        foreach ($model->elements as $name => $element) {
            if (!$element instanceof \atk4\data\Field) {
                continue;
            }
            
            $searchFields[] = $name;
        }
        $crud->addQuickSearch($searchFields);
        $crud->quickSearch->owner->add(new \atk4\ui\FormField\Input(['inputType' => 'Hidden', 'short_name' => 'crud_model', 'content' => get_class($model)]));

Then when I open the Grid, write some search text and press Search, the following Exception is fired:

    atk4\dsql\Exception: DSQL got Exception when executing this query
    Exception Parameters
        error: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_sql' in 'where clause'"
        query: "select count(*) from `fromatk4_country` where (`id` like '%s%' or `created_at` like '%s%' or `notes` like '%s%' or `iso_code` like '%s%' or `name` like '%s%' or (CONCAT(`iso_code`, ' - ', `name`)) like '%s%' or `field_sql` like '%s%')"

It seems there is a wrong column name in the SQL query (`field_sql`). This problem came up one I upgraded to the atk4/data 1.3.5 from some version from last year.

Is this a bug or should/can I inicialize the search fields differently?

**Comment by DarkSide666** [comment]
Can you try this way?

Instead of
```
   // add quick search
    $searchFields = [];
    foreach ($model->elements as $name => $element) {
        if (!$element instanceof \atk4\data\Field) {
            continue;
        }
        
        $searchFields[] = $name;
    }
```

Simply
````
$searchFields = array_keys($model->get());
```

Also I don't see where you have Field_Callback used. Can you add whole model code here or at least that part which involves Field_Callback?

**Comment by mvorisek** [comment]
The `$searchFields = array_keys($model->get());` code provides exactly the same.

I checked my and Atk code and found something very interesting.

When the search `$searchFields` array is assigned before `$crud->setModel()`, then it works.

Exactly is does not work after `$this->initUpdate();` in `$crud->setModel()`. Once the `initUpdate()` method is called, 1 extra field called `field_sql` is added!

Here is what I found by debugging the `initUpdate()` method:

a) add:

    print_r(array_keys($this->model->get()));

just after the method definition.
Result: works as expected.

b) add:

    print_r(array_keys($this->model->get()));

after the first line `$this->addAction(['icon' => 'edit'], new jsModal(...`.
Result: One additional field named `field_sql` is added to the model.

There is some issue in the `Grid::addAction()` method as I tried to isolate the problem by replacing the first line with:

    $this->addAction(['icon' => 'edit'], null);

and the result is the same as in b) (unexpecly added new field to the model).

Can you confirm this issue or is this "by design"?

**Comment by romaninsh** [comment]
This seems like a bug.

**Comment by romaninsh** [comment]
Actually - rereading the bugreport.

By Callback you mean PHP one? If yes, than it can't be searched. Expression can be searched, but not callback, because we use "where()" for searching.

**Comment by DarkSide666** [comment]
Field\Callback fixed by https://github.com/atk4/data/pull/385, but that probably don't solve anything here.

**Comment by DarkSide666** [comment]
Tested - this way it **works fine** for `Grid`:
```
$g = $app->add(['Grid']);
$m = new Country($db);
$m->addExpression('test', ['CONCAT([iso3], \' - \', [name])']);
$g->setModel($m);
$g->addQuickSearch(['name','test'], true);
```

Tested - this way it **works fine** for `CRUD`:
```
$g = $app->add(['CRUD']);
$m = new Country($db);
$m->addExpression('test', ['CONCAT([iso3], \' - \', [name])']);
$g->setModel($m);
$g->addQuickSearch(['name','test'], true);
```
