### ISSUE TITLE
iterating over a hasOne reference causes all referenced records to be loaded

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/data#335]
Hi there,

I have a view which iterates over the model set via setModel in a foreach loop. Typically, a hasMany reference is passed, something like `$view->setModel($tour->ref('GroupToTour'));`

When passing a hasOne reference to this view though, the foreach causes an unintended behaviour:

```
Model Tour hasOne pack_list_id
$view->setModel($tour->ref('pack_list_id'));
```

When doing this,  the foreach loop iterates over all PackList records. The SQL produced is:
`select `id`,`created_date`,`created_by`,`file_id` from `pack_list` `pl``

Though I know that passing a hasOne reference to a foreach loop is not too sensible, this seems wrong to me. I would expect the foreach loop to loop over one record if pack_list_id is set, or dont do anything if the pack_list_id is null. Image some code like this :)
```
foreach($this->ref('someHasOneReference') as $m) {
    $m->delete();
}
```

Heres a simple code example causing what is described above:
```
$tour = new \Pmg\Tour($app->db);
$tour->load(145);
$pl = $tour->ref('pack_list_id');
var_dump($pl->loaded());
foreach($pl as $p) {
    echo $p->get('id');
}
```

**Comment by DarkSide666** [comment]
Well... This is good issue you have found, but it looks quite hard to fix. It will require refactoring Reference classes and that way can break something else in other projects.

Basically idea is:
* hasMany - adds condition so is safe for iterator
* hasOne - loads related record and if it's loaded, then don't add any condition, so iterator will iterate over all data set
* hasOne in deep traversal - in this case record is not loaded, for example $m->ref('many')->ref('one_id') and then it will act like hasMany reference, it will add condition.

**Comment by PhilippGrashoff** [comment]
Thought this was a bigger thing. It's just that ref() behaves entirely different depending on the relation type.
I will check refLink() and maybe use this instead of ref() for has One relationships.

Regarding deep traversal, if the first element is a hasOne relationship, conditions are not added, too

**Comment by DarkSide666** [comment]
yes. it's because of for example DropDown field.

`$model->hasOne('foo_id', new Model_Foo());`
What you would expect $model->ref('foo_id') return? It will return Model_Foo of course, but it can't set any conditions on it because otherwise, for example, in DropDown you have to show all records from Model_Foo, not just one (already loaded one).

Changing something there requires full Agile/Data refactor and that will not happen sometime soon I guess.

**Comment by PhilippGrashoff** [comment]
I get it that this would be a huge change :) I use ref() a lot, usually with hasMany relations, and was quite suprised about the different behaviour.

Will look into refLink() and refModel() functions also to get a deeper understanding.

Regarding the dropdown: I would have expected it to use refModel() which returns the model without conditions if I get it correctly :)
