### ISSUE TITLE
Model::ref() does not apply condition on hasMany Reference if Model is not loaded

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/data#355]
Have a look at this code:
```
$g = new \EOO\Data\Group($this->app->db);
foreach($g->ref('GroupToTour') as $t) {
    echo $t->get('id').PHP_EOL;
}
```

Definition inside Group::init(), GroupToTour is a hasMany relation:
```
$this->hasMany('GroupToTour',   new GroupToTour());
```

And the definition of the relation on GroupToTour::init()
```
$this->hasOne('group_id',  new Group());
```

I'd expect to have a newly created record no relations at all.
Instead, the code above iterates over all GroupToTour records there are, so no conditions are set on the reference.
If I $g->save() before the foreach, everything works as expected.

**Comment by DarkSide666** [comment]
This is correct as it works I think.

1. If Group model is loaded, then it will select only GroupToTour records for that particular Group.

2. If Group model is not loaded, then it will select *all* GroupToTour records which are related to *any* Group record.

You can play with that by adding this test in /atk4/data/tests/smbo/TransferTest.php for example:
```
    public function testWhatever()
    {
        // create accounts and payments
        $a = new Account($this->db);
        
        $a->save('AIB');
        $a->ref('Payment')->save(['amount'=>10]);
        $a->ref('Payment')->save(['amount'=>20]);
        $a->unload();
        
        $a->save('BOI');
        $a->ref('Payment')->save(['amount'=>30]);
        $a->unload();
        
        // create payment without link to account
        $p = new Payment($this->db);
        $p->saveAndUnload(['amount'=>40]);
        
        // Account is not loaded, will dump all Payments related to ANY Account
        foreach ($a->ref('Payment') as $t) {
            var_dump($t->get());
        }

        // Account is loaded, will dump all Payments related to that particular Account
        $a->load(1);
        foreach ($a->ref('Payment') as $t) {
            var_dump($t->get());
        }
    }
```

**Comment by DarkSide666** [comment]
Added this test in this PR for future reference: https://github.com/atk4/data/pull/357

**Comment by PhilippGrashoff** [comment]
HI Imants,

if thats the way ref() is meant to be, ok :) I just think this can accidently lead to very dangerous code, something like:
```
foreach($m->ref('someHasManyReference') as $ref) {
    $ref->delete();
}
```
When $m is not loaded, this code will quite surely **** up a lot of data.
IMHO I think a function that always only returns the referenced records no matter if the model is loaded or not or the reference type would be great as it can't be accidently misused (see also #335).
Maybe thats something for V2?

Perhaps leave this issue open and I will document the behaviour of ref() more detailed in Docs, you can assign me to this if you think this is a good idea.
