### ISSUE TITLE
Cannot save in lastest version fields error:  Attempting to change read-only field

### ISSUE THREAD

**Issue by rapgithub** [atk4/data#356]
When using save the data a strange hidden field is showing all the time at the bottom of all the forms...

FIELD SQL

and when using it with filestore now I see all the hidden fields of filestore showing up too and I cannot save because of this error: see the attached file

Any solution?
thanks!

<img width="884" alt="screenshot 2018-11-18 at 19 16 53" src="https://user-images.githubusercontent.com/11996194/48676391-a3142c80-eb66-11e8-8335-d89f889babe8.png">

**Comment by DarkSide666** [comment]
Field SQL showing up bug will be fixed here: https://github.com/atk4/ui/pull/597

**Comment by DarkSide666** [comment]
1. Which filestore addon do you use?
2. Show me your data model.
3. add `'ui'=>['form'=>['visible'=>false]]` in your data model for these fields.

**Comment by rapgithub** [comment]
Lastest version online 4 days ago I did it via composer

but I have to modify the composer.json with   "minimum-stability": "dev" and
  "prefer-stable": false to be able to install it...

```
{
  "minimum-stability": "dev",
  "prefer-stable": false,  
  "require":{
    "atk4/ui": "^1.2",
    "atk4/login": "^1.0",
    "atk4/filestore": "dev-master",
    "atk4/mastercrud": "dev-master"
  }
}
```

Also I saw that I had to came back to my old file store as well because of some problems with the new version and also use an old version of mastercrud due to this issue...

so using and old version not the new working code I have:
```
$img = $this->addField('img', [new \atk4\filestore\Field\File(), 'type' => 'file', 'caption'=>'INSPIRE IMAGE - [ex. Upload JPG Files]']);
```

**Comment by DarkSide666** [comment]
That's exactly what I thought - you don't use atk4/filestore addon at all and this issue actually should be in atk4/ui repo.

**Comment by rapgithub** [comment]
OK sending soon...

**Comment by rapgithub** [comment]
here my complete code for uploading file using mastercrud and filestore
```php


include 'vendor/autoload.php';
use \atk4\data\Model;
include 'db.php';

use League\Flysystem\Filesystem;
use League\Flysystem\Adapter\Local;

$app = new App(false);

if ($app->auth->user->loaded()) {

  class AllEvents extends Model {
    public $table = 'all_events';
    public $title = 'All Events';


      function init() {
          parent::init();

          $this->addField('name');
          $this->hasMany('Images', new Images());

      }
  }

  $adapter = new Local(__DIR__.'/localfiles');

  $app->filesystem = new Filesystem($adapter);

  class Images extends Model {
      public $table = 'all_events_images';
      public $title = 'All Events Images';

      function init() {
          parent::init();

          $this->addField('img', new \atk4\filestore\Field\File($this->app->filesystem));

          //$this->addField('img', new \atk4\filestore\Field\File());

          $this->hasOne('all_events_id', [new AllEvents(), 'ui'=>['visible'=>false]])->addTitle();

          $this->addHook('beforeSave', function ($m) {

          });

      }


      public function validate($intent = null)
          {
              $errors = parent::validate($intent);

              return $errors;
      }

  }

  $crud = $app->add([
      '\atk4\mastercrud\MasterCRUD',
      'quickSearch'=>['name'],
      'ipp'=>5,
      'fieldsRead'=>['name'], // only field 'name' will be visible in table
  ]);

  $crud->setModel(new AllEvents($app->db),

  ['Images'=> ['CRUD', 'quickSearch'=>false, 'canDelete'=>true, 'canUpdate'=>true, 'fieldsRead'=>['all_events'] ]]

  );




} else {

      	$t = $app->add(['Message', 'not connected','warning'])->text;
        $app->add(['Button', 'back'])->link(['index']);

}


```

QUESTIONS:
1)
Is it possible to make the Add New **AllEvents** inside the circle I marked to show it as defined in  $title?

```php
public $title = 'All Events';
```

<img width="1177" alt="screenshot 2018-11-21 at 02 05 15" src="https://user-images.githubusercontent.com/11996194/48812365-51200200-ed32-11e8-84b6-cb00156a8ba5.png">

1a)
here another screenshot showing the screen after I clicked the event 2018 link, there is no issues here yet....

<img width="1176" alt="screenshot 2018-11-21 at 02 05 27" src="https://user-images.githubusercontent.com/11996194/48812481-d86d7580-ed32-11e8-92ad-07bc4338b5e1.png">

1b) 
here another screenshot showing the screen after I clicked All Event Images Tab link, there is no issues here yet....

<img width="1180" alt="screenshot 2018-11-21 at 02 05 33" src="https://user-images.githubusercontent.com/11996194/48812535-123e7c00-ed33-11e8-886f-f8316f92c76d.png">


2) here another screenshot showing the screen after I click Add New Images, the problem as you see it is showing hidden/readonly fields that after choosing the image and trying to save it it shows the error for those fields in red...

see the screenshots:


<img width="957" alt="screenshot 2018-11-21 at 02 05 40" src="https://user-images.githubusercontent.com/11996194/48812619-81b46b80-ed33-11e8-800c-e565b593470f.png">


<img width="928" alt="screenshot 2018-11-21 at 02 05 50" src="https://user-images.githubusercontent.com/11996194/48812626-8aa53d00-ed33-11e8-9e9f-9b64872919d5.png">
 


my composer:
```json
{
  "minimum-stability": "dev",
  "prefer-stable": false,
  "require":{
    "atk4/ui": "^1.6",
    "atk4/data": "^1.3",
    "atk4/login": "^1.0",
    "atk4/mastercrud": "dev-master",
    "atk4/api": "^0.1.0",
    "atk4/filestore": "dev-master",
    "league/flysystem": "^1.1@dev"
  }
}
```

any solution?

**Comment by rapgithub** [comment]
Patching the columns.php file inside ui/src/formLayouts/Columns.php it solves the issue with those hidden/readonly fields showing and generating the error:

I only replaced the Columns.php putting and old version of it... and solved the issue...

here the good working file 

```php

<?php

namespace atk4\ui\FormLayout;

use atk4\ui\Form;

/**
 * Layout that automatically arranges itself into multiple columns.
 * Well suitable for large number of fields on a form.
 */
class Columns extends Generic
{
    public $col = null;
    public $size = '';

    public function setModel(\atk4\data\Model $model, $fields = null)
    {
        // dont add any fields automatically
        parent::setModel($model, false);

        if ($fields === null) {
            $fields = [];
            foreach ($model->elements as $f) {
                if (!$f instanceof \atk4\data\Field) {
                    continue;
                }

                if (!$f->isEditable()) {
                    continue;
                }
                $fields[] = $f->short_name;
            }
        }

        $cnt = count($fields);

        if ($this->col !== null) {
            $col = $this->col;
            $size = $this->size;
        } elseif ($cnt < 10) {
            $col = 1;
            $size = '';
        } elseif ($cnt < 15) {
            $col = 2;
            $size = '';
        } elseif ($cnt < 20) {
            $col = 2;
            $size = 'small';
        } elseif ($cnt < 32) {
            $col = 3;
            $size = 'small';
        } else {
            $col = 4;
            $size = 'tiny';
        }

        if ($size) {
            $this->form->addClass($size);
        }

        $c = $this->add('Columns');

        $chunks = array_chunk($fields, ceil($cnt / $col));
        foreach ($chunks as $chunk) {
            $cc = $c->addColumn();
            $cc->add(['FormLayout/Generic', 'form' => $this->form])->setModel($model, $chunk);
        }

        $this->add(['ui' => 'clearing hidden divider']);

        return $model;
    }
}

```

**Comment by rapgithub** [comment]
Another thing if I use my old columns.php file to solve that issue with readonly fields and hidden fields saving the record then it is not a problem anymore but the issue I found then it is mastercrud not showing the **fieldsread** I want to display for the Images model and instead showing **name** that belongs to the table **all events**

here the screen shot

<img width="1185" alt="screenshot 2018-11-21 at 02 56 50" src="https://user-images.githubusercontent.com/11996194/48813990-6d736d00-ed39-11e8-9f53-2e881123b584.png">

If I click this **name** column marked in circle in the screenshot above I see this error:

<img width="988" alt="screenshot 2018-11-21 at 03 01 18" src="https://user-images.githubusercontent.com/11996194/48814099-d0fd9a80-ed39-11e8-921d-f77d99fb072e.png">

any solution? 

again composer.json it is 

```json
{
  "minimum-stability": "dev",
  "prefer-stable": false,
  "require":{
    "atk4/ui": "^1.6",
    "atk4/data": "^1.3",
    "atk4/login": "^1.0",
    "atk4/mastercrud": "dev-master",
    "atk4/api": "^0.1.0",
    "atk4/filestore": "dev-master",
    "league/flysystem": "^1.1@dev"
  }
}
``

**Comment by DarkSide666** [comment]
First of all - don't try to solve every of your problem in this one Github issue. And we will not solve everything for you too :)

Second - is the code you posted here compilation from multiple files? If not then I must say it's a real mess you have there :)

Third - about hour ago we merged some fixes in atk4/ui in develop branch which will fix at least that "field sql" error. Please do composer update.

And now to wrap this up:
1. please don't overcomplicate things here
2. we need simple test cases (no spaghetti code, no useless rows etc) which fails and which we can fix (or explain)
3. every issue should go in respective repository. UI issues atk4/ui, Data issues atk4/data, Filestore issues atk4/filestore and so on.

**Comment by romaninsh** [comment]
I agree with @DarkSide666. This issue is too confusing. I'm not sure what it is about anymore. 

We offer a good rate for ATK commercial support, @rapgithub if you want to help ATK please email support@agiletoolkit.org. That helps us keep the project moving forward and we can work on specific solution for you.

**Comment by rapgithub** [comment]
Sorry I thought you needed full data model definition with the code... my mistake putting all together in one post! 

best regards! and thank you for the support offered romaninsh!

**Comment by romaninsh** [comment]
Github should be strictly for bugreports but we try to be helpful and it becomes a bit of a "support" :)

**Comment by rapgithub** [comment]
thank you for the attention guys! I must keep it simple the better ... sorry my mistake! 👍
