### ISSUE TITLE
\atk4\data\Field_Callback does not exist

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#363]
In the latest release, in `\atk4\data\Model` and \atk4\data\Reference_Manyl classes there is a reference to `\atk4\data\Field_Callback`, but this class does not exist.

The right name should be `\atk4\data\Field\Callback`. Or Refactor the Callback field class to `Field_Callback`.

**Comment by romaninsh** [comment]
how is this not spotted by test-suite?

**Comment by romaninsh** [comment]
@mvorisek can you provide specific example?

**Comment by mvorisek** [comment]
> 
> 
> @mvorisek can you provide specific example?

https://github.com/atk4/data/blob/30ba303e8f060e2f7244395e2ee9a82eddae7b9c/src/Model.php#L51 see this line, the class does not exist

**Comment by mvorisek** [comment]
In general it would be nice if the PHP standard syntax can be used:

`MyClass::class`

Currently absolute class name in Atk4/* libs needs to be prefixed with `\`. What about converting all "text-wired" class names to `Ns\Class:class` and resolving them as an absolute? Or firstly try to resolved relative to the default Atk4 impl and if no match is found, use them as an absolute path.

**Comment by romaninsh** [comment]
@mvorisek We're trying to keep ATK Data modern and refactor away "old style" code where possible. With that in mind, Field\Callback is preferred over Field_Callback etc.

The property is redefined in the SQL persistences, but we didn't get chance to properly test references in outside of that. So with that in mind, the PR to fix this issue should:

 - Come with a test-cases.
 - Use Field\Callback 

A separate PR could replace string class names with `Ns\Class:class`.

**Comment by romaninsh** [comment]
I looked further into Ns\Class::class approach. It looks cool, however it's nothing other than a string without leading backslash "Ns\Class". I'll give it a try at some point.

**Comment by DarkSide666** [comment]
Fixed by this https://github.com/atk4/data/pull/385
