### ISSUE TITLE
Model: $this->set($this->id_field, $this->id) after insert

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/data#365]
Hi,

will create a pull request for this right after I published this here.
In atk4\data\Model::save(), after inserting a record to the database the id given from persistence is stored in $this->id, but its not populated to the field of the model.
So, if reload_after_save is set to false or if some other action should be done with the model inside the afterInsert hook, Model->get('id') will return null though this value is available and stored in db.
setting it by $this->set($this->id_field, $this->id) will make Model->get('id') return the correct value always.

**Comment by romaninsh** [comment]
Philipp, can you provide a valid test-case for this case inside your PR? Just to illustrate the error.

**Comment by PhilippGrashoff** [comment]
Hi, will provide a sensible testcase tomorrow, going to bed now. Its only insert-related. 
Test case will look someway like this:
```
$m = new SomeModel($persistence);
$m->reload_after_save = false;
$m->addHook('afterSave', function($m) {
    //in afterSave, I'd expect the ID field to be always populated no matter what happened before
    if(is_null($m->get($m->id_field))) {
        throw new \atk4\data\Exception('Damn, no ID available');
    }
});
$this->expectException(\atk4\data\Exception:class);
$m->save();
```

**Comment by romaninsh** [comment]
Yes, it would be nice to see model definition. Technically - Reload calls load() and that one should populate ID field properly, so something is messed up with model definition.

**Comment by PhilippGrashoff** [comment]
Hi,
if reload() is called inside save(), everythings fine. But If not (as in code above due to reload_after_save = false), ID field is not populated (while $this->id is). It Seems wrong to me to have id set in the property but not in the field.

**Comment by romaninsh** [comment]
AHH i understand now, what the case is. Yes, this should be addressed, otherwise it is inconsistent.

**Comment by DarkSide666** [comment]
Well, I am not so sure it's a bug otherwise we wouldn't need $model->id property at all.

My understanding is that if model is not re-loaded (or not loaded at all), then it should be "empty". That means all fields including id field should be empty.
$model->id is left set only because we need it for afterSave hook and most likely should be set to null also after afterSave hook execution (if it's not done yet).

**Comment by PhilippGrashoff** [comment]
I too find it a bit puzzling why there is the id property as well as the id_field field.

But as someone who uses this code, its
1) pretty strange that Model->id is set, but Model->id_field Field not.
2) Not having $this->get('id') available after save without reload leads to some ugly workaround code like:
```
if($this->get('id') === null && $this->id) {
    $this->set('id', $this->id);
}
```
3) with this new line, there is no need to have to use the id in afterInsert hook as separate parameter as its set already. Like this code in hooks can be more consistent, only having Model as parameter (apart from beforeInsert and beforeUpdate which are different). Having all hooks having the same code one day surely would make things easier.

**Comment by romaninsh** [comment]
technically you should always `$this->id`. The fact that you have a field with "id" is purely coincidental. in some cases it could be "_id" or "ID" or unavailable.

**Comment by PhilippGrashoff** [comment]
meant to keep that code above relative using `$this->id_field` instead of 'id'. Changed it.
Or did you mean `$this->id_field`? :)

Using the $this->id property makes the resulting code inconsistent.
While every other field of the model is addressed using `$this->set()`, `$this->get()`, (or using array access), The id field is addressed using a property of the model.

**Comment by DarkSide666** [comment]
Ah. Actually I misunderstand this change a bit.

I am fine with this. It will only affect `reload_after_save=false` case.
