### ISSUE TITLE
our_field is honored in Reference impl, but on save a validation error is thrown

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#370]
If different `our_field` than `link` name is used in Reference, currently on save the Model::normalizeFieldName method will throw an error (Field is not defined inside a Model).

What does the Model::isDirty method expects? Field name (i.e. `link`) from model, or the real column name (i.e. `our_field`)?

If the real column name is expected, it can be fixed in the Reference_SQL_One code on these lines:
https://github.com/atk4/data/blob/e2eac934a53dac45d8104194bdd3ab14b7076ea3/src/Reference_SQL_One.php#L32
https://github.com/atk4/data/blob/e2eac934a53dac45d8104194bdd3ab14b7076ea3/src/Reference_SQL_One.php#L222

In the first mentioned line the if condition is probably also a typo - please double check, currently never satisfied (res && !res).

**Comment by DarkSide666** [comment]
Line 32 surely is a bug.
