### ISSUE TITLE
Implementation of User-level Actions

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#382]
Although on the basic level models can perform "CRUD" operations (create, read, update and delete), in reality there are many other actions.

Currently you have to create method inside a model, but it's hard for the other components to discover which methods are safe to execute.

I propose we implement hook `getActions` that would return array of special action objects. So your model `Package` could be like this:

```
$this->addHook('getActions', function($m) {
    return [
        'delivered' => new Action("Signed for Delivery", function($m){ 
            return $m->save('delivered', true);  
         })
   ] 
});
```

Second argument is optional and if not specified then $m->delivered() is called. Class `Action` could be initially quite simple, but then we can add all sorts of properties to it - is at a dangerous action? What arguments are required? etc.

This action would be safe to exported through UI or API frameworks as a button or a POST end-point.

**Comment by PhilippGrashoff** [comment]
Hi,
interesting Idea. So e.g. CRUD would automatically add Buttons for the actions defined here.

As I am about to implement user role rights on the data level (currently its only on UI level and thats crap of course), this could be a way to set which user role may perform which actions?

**Comment by romaninsh** [comment]
@PhilippGrashoff - yes. And I am planning to have mechanism which would detect if action is permitted before actually executing it. This would work with https://github.com/atk4/login/pull/15.

**Comment by abbadon1334** [comment]
good because can be linked with key to ACL rules, but the name action is already used in model for std actions, procedure can be misunderstood in DB stored procedures, special actions is too long, what you think about Task? even this in general is trivial but in Model give the idea of something to do and give a result. Naming is philosophy ;)

**Comment by abbadon1334** [comment]
what you think about this?

![image](https://user-images.githubusercontent.com/5801824/53098685-dd59e500-352c-11e9-9b8e-473c1d70a933.png)

**Comment by mvorisek** [comment]
UserAction is implemented
