### ISSUE TITLE
Not using public variable

### ISSUE THREAD

**Issue by gowrav-vishwakarma** [atk4/data#404]
https://github.com/atk4/data/blob/27c615449917bc7acc13968b54ea006177b66633/src/Model.php#L379

Here, if we try to override Field Class with our one, it is just not used here and it just became static.

**Comment by DarkSide666** [comment]
Not sure what you mean there? Can you give example code?

`$model->addField('foo', new MySpecialField())` should work. I've used that quite a lot.

**Comment by gowrav-vishwakarma** [comment]
Hi, That looks like an answer. Let me try this and I'll update about it here.

**Comment by DarkSide666** [comment]
More than 2 months, no update. Closing.
