### ISSUE TITLE
Model::addExpression typecast/normalization issues with int = 0 and never_persist = true

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/data#408]
Hi there,
I just discovered this:
In one of my models, I add an Expression like this:

```
 $this->model->addExpression('ctc_is_approved', [$this->model->expr("(SELECT `is_approved` FROM `company_to_calendar` WHERE `company_id`= [] AND `calendar_id` = `calendar`.`id`)", [$this->app->auth->user->get('id')]), 'type' => 'integer', 'system' => true]);
```
   
In this case, if `is_approved` is set to 0 (zero) in mysql, it gets casted/normalized correctly and represented as int(0) in PHP. However, adding `never_persist => true` to this expression changes this:

```
 $this->model->addExpression('ctc_is_approved', [$this->model->expr("(SELECT `is_approved` FROM `company_to_calendar` WHERE `company_id`= [] AND `calendar_id` = `calendar`.`id`)", [$this->app->auth->user->get('id')]), 'type' => 'integer', 'system' => true, 'never_persist' => true]);
```

Now, if `is_approved` is set to 0 (zero) in mysql, it gets casted/normalized to `NULL` instead of int(0).
Didnt dig deeper into this yet, maybe `never_persist => true` skips persistence typecasting/normalization when loading?

Best regards
Philipp

**Comment by romaninsh** [comment]
possibly related to #414

**Comment by romaninsh** [comment]
May be a violation of https://github.com/atk4/data/wiki/ADP1904---Typecasting-and-serialization-cleanup

**Comment by DarkSide666** [comment]
I can reproduce this issue.

**Comment by DarkSide666** [comment]
This is as expected. In your case you should use `never_save` instead of `never_persist`.

`never_save` - loads data (execute expressions), but do not save data
`never_persist` - don't load and don't save data. As result expression will not be executed because this field will not be loaded at all.

Testcase added in https://github.com/atk4/data/pull/792
