### ISSUE TITLE
Persistence\Array_ don't support action(field)

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#415]
```
$p = new Persistence\Array_($data);
$m = $p->add(new Model());

// here model (references) will try to call $m->action('field', ['id'])
// but array persistence don't support action 'field'
$view->setModel($m, null);
```

on the other hand `$view->setModel($m, false);` will work fine without invoking action(field), so it's not urgent thing to fix.

**Comment by romaninsh** [comment]
- is $view instance of View class? 
 - if you load $m, does it have any difference?
 - $m = new Model($p) - still not working?

**Comment by DarkSide666** [comment]
such action wasn't implemented in array persistence at all
