### ISSUE TITLE
Model->exist() and existBy()

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#432]
**Use case**

Most of the time your models will contain a lot of fields which are calculated or selected by subselects and this can be a bit slow. It's of course required if you want to work with all model fields further on, but what if you just want to test if record with such ID or by some value in particular field exist at all? In this case calling huge select with all subselects is a big overhaul if you just want to check if invoice with particular ref_no exist or not.

**Solution**

New methods: `Model->exist($id)` and `Model->existBy($field, $value)`

```
function exist($id) {
    return $this->existBy($this->id_field, $id);
}
function existBy($field, $value) {
    return $this->newInstance()
        // ->onlyFields(array_unique(array_merge([$this->id_field],[$field]))) maybe just like below for simplicity
        ->onlyFields([$this->id_field, $field])
        ->tryLoadBy($field, $value)
        ->loaded();
}
```

**Comment by romaninsh** [comment]
can be easily done by method injection and persistence hook, so:
 1. implement in your project
 2. create external add-on
 3. if add-on is really popular, we can implement native methods.
