### ISSUE TITLE
In current dev branch: Condition on reload after save make save fail

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/data#434]
Hi there,

In the current dev branch, I discovered this behaviour:

```
$group->set('status', 'booked');
$group->save();
$groups = new Group($app->db);
$groups->addCondition('status', booked');
foreach($groups as $g) {
    $g->set('status', 'completed');
    //here Exception will be thrown
    $g->save();
}
```

When the model is reloaded after save, the conditions are applied on the model. As the status of the current record is not 'booked' any more, the current record is not within the conditions. This causes an Exception. Strangely, the exception does not show the Condition, yet the SQL carries it:

```
Fatal Error
atk4\data\Exception: Record was not found
Code
404
Exception Parameters

    model: Object EOO\Data\Group
    id: "15"
    conditions: 

File | Object | Method
-- | -- | --
vendor/atk4/data/src/Persistence/SQL.php: 732 | atk4\data\Exception | atk4\core\Exception::__construct()
anagement/vendor/atk4/data/src/Model.php:1095 | atk4\data\Persistence\SQL | atk4\data\Persistence\SQL::load()
anagement/vendor/atk4/data/src/Model.php:1120 | EOO\Data\Group | atk4\data\Model::load()
vendor/atk4/data/src/Persistence/SQL.php: 937 | EOO\Data\Group | atk4\data\Model::reload()
anagement/vendor/atk4/data/src/Model.php:1557 | atk4\data\Persistence\SQL | atk4\data\Persistence\SQL::update()
: | EOO\Data\Group | atk4\data\Model::atk4\data\{closure}()
ment/vendor/atk4/dsql/src/Connection.php: 281 | - | call_user_func()
vendor/atk4/data/src/Persistence/SQL.php: 124 | atk4\dsql\Connection_Dumper | atk4\dsql\Connection::atomic()
anagement/vendor/atk4/data/src/Model.php:1933 | atk4\data\Persistence\SQL | atk4\data\Persistence\SQL::atomic()
anagement/vendor/atk4/data/src/Model.php:1611 | EOO\Data\Group | atk4\data\Model::atomic()
w/html/TourManagement/src/Data/Group.php: 615 | EOO\Data\Group | atk4\data\Model::save
  | (                    )

```

In previous versions of ATK data, this worked. WIll dig deeper into it.

**Comment by PhilippGrashoff** [comment]
A kind of 'proof' is that this works:
```
$group->set('status', 'booked');
$group->save();
$groups = new Group($app->db);
$groups->addCondition('status', booked');
foreach($groups as $g) {
    $g2 = new Group($app->db);
    $g2->load($g->id);
    $g2->set('status', 'completed');
    $g2->save();
}
```

**Comment by DarkSide666** [comment]
This is _as expected_, but only issue here is that Exception don't show condition, right?

**Comment by PhilippGrashoff** [comment]
well, I'd say the issue is that save() does throw an exception during reloading after save :). 

Thinking this further, it would actually mean that whenever saving a model record with conditions set, it could fail as conditions might not be set. In my opinion, if the save itself was successfull the reload should always work.

Some versions ago, the same code worked. I will go down the last ATK data commits and check in which commit the change happened.

**Comment by DarkSide666** [comment]
Why? It can't reload record because it don't match condition, so that's kind of normal.
I think that didn't (shouldn't) work like that before too.

Imagine that you have:
```
$unpaid_invoices = (clone $invoice)->addCondition('paid', false);
$unpaid_invoices->loadAny();
$unpaid_invoices->set('paid', true);
$unpaid_invoices->save(); // this SHOULD throw exception !
// but if it doesn't, then we have inconsistent model object at the end

$unpaid_invoices->get('paid');
// this will return true even if model have condition set that
// only unpaid invoices should be included in this data-set
```

**Comment by PhilippGrashoff** [comment]
This will be my next atk headache :) :) :)
I am still thinking too much of a model as a single record, not as a bunch of records. In my thinking, if I save a single record, it should always be able to reload that single record...

But when thinking of model as a bunch of records always, then yes, you're right. I will figure which commit made my code that worked previously, just dont have time for it now.

Wondering about a good solution for this then:
I want to set all groups from 'booked' to 'finished' if field 'end_date' is older than 10 days. The best way to do this is:
```
$group->set('status', 'booked');
$group->save();
$groups = new Group($app->db);
$groups->addCondition('end_date', '<',( new \DateTime())->modify('-10 Days');
$groups->addCondition('status', booked');
$g_without_conditions = $group->newInstance();
foreach($groups as $g) {
    $g_without_conditions->load($g->id);
    $g_without_conditions->set('status', 'completed');
    //here Exception will be thrown
    $g_without_conditions->save();
}

```
Not very performant....

**Comment by PhilippGrashoff** [comment]
That code above is crap. Dont have time this evening, need to focus on something else. Will get back to you.

**Comment by funyx** [comment]
@phillip could you write the code above in some of the persistence tests

**Comment by romaninsh** [comment]
That's as expected and is making sure you don't mess things up. There are two CORRECT ways around it:

1. saveAs('model with correct condition')
2. saveAndUnload()

In your case it's easier and faster to use second approach.

**Comment by PhilippGrashoff** [comment]
Thanks for hints. I had the call to save() 2 method calls "away" from the addCondition() code and I was wondering how to "protect" that save() to work whenever there are conditions.
My summary for this is that save() should be called from same code as addCondition() to make sure that the save() will work.
There are some cases though where this will hardly be possible, guess there's some luck involved in never calling these save()'s which conditions that make reload invalid :)
