### ISSUE TITLE
Docs: Defining references with ModelName::class

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/data#435]
Hi there,

after Romans mentioned somewhere in our Weekly hangout that references should be defined like 
```
$this->hasOne('some_model_id', SomeModel::class);
$this->hasMany('SomeModel', SomeModel::class);
```
I started thinking about this. So far I used what is mainly spread in the docs:
```
$this->hasOne('some_model_id', new SomeModel());
$this->hasMany('SomeModel', new SomeModel());
```
Which means that everytime you instanciate an object, an instance of SomeModel (in this case 2) will also be created right away, even if the reference is never used.
Of course, this is unneccessary, so I altered my code today. I use a lot of references and the results of this refactor left me mouth-open: **my Testsuite only takes 60% of the time it used before!**

I will take care of updating the docs.

**Comment by romaninsh** [comment]
hehe, yeah!

**Comment by DarkSide666** [comment]
Yeah ! That's exactly why we should use `Model::class` syntax there as much as possible.
Actually the only exception is if you work with multiple persistences and need to specify exactly which persistence to use for related model. That's the case with `containsOne` and `containsMany` for example.

**Comment by DarkSide666** [comment]
It's now documented in here https://github.com/atk4/data/pull/419

**Comment by PhilippGrashoff** [comment]
If you need to add some conditions on the referenced model, put it inside a function. This way the object also is only instanciated if the reference is  used, e.g. like here:
```
        $this->hasMany('SomeRefModelWithConditions',     [
            function() {
                return (new SomeRefModelWithConditions($this->persistence))->addCondition('model_class', get_class($this));
            },
            'their_field' => 'model_id']);
```

**Comment by DarkSide666** [comment]
yeah

**Comment by DarkSide666** [comment]
Done in #419
