### ISSUE TITLE
Default value of fields is not respected

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/data#449]
Hi,
actually I wanted to create a PR, but Github only wants me to compare branches when I try to.

So:
Fields have a property "default", but its actually not used. I think the right place to check if a default value is set is in Field::get().
Here would be a solution:
```
    public function get()
    {
        if($this->owner[$this->short_name] !== null) {
            return $this->owner[$this->short_name];
        }
        elseif($this->default) {
            return $this->default;
        }
        return null;
    }
```

**Comment by PhilippGrashoff** [comment]
And a test for it:
```


    public function testDefaultValue()
    {
        $m = new Model();
        $m->addField('nodefault');
        $m->addField('withdefault', ['default' => 'abc']);
        $this->assertEquals(null, $m->get('nodefault'));
        $this->assertEquals('abc', $m->get('withdefault'));
    }
```

**Comment by romaninsh** [comment]
https://github.com/atk4/data/blob/develop/tests/FieldTest.php#L192 - useless...

**Comment by romaninsh** [comment]
relevant: https://github.com/atk4/data/blob/develop/tests/FieldTest.php#L155

**Comment by abbadon1334** [comment]
IMHO the only point where it can happens is here => https://github.com/atk4/data/blob/ffd55c988c16299d45f13c2d0fd5ad4520746f0e/src/Model.php#L853

**Comment by DarkSide666** [comment]
If I understood correctly then proposal is to move `$field->default` functionality from Model to Field class itself?

**Comment by abbadon1334** [comment]
check this @PhilippGrashoff https://github.com/atk4/data/tree/add-defaults-unit-test

@DarkSide666 feel free to merge it as specific test for defaults : model & fields

i add unit test and defaults works as excepted

**Comment by PhilippGrashoff** [comment]
@DarkSide666 reading through the code that seems to be the way it is: 
```
Currently $model->get('foo') will return fields default value, but $model->getField('foo')->get() will not? Right?
```
I noticed a Form didnt use default values any more, at least a DropDown didnt. Will check again.

**Comment by PhilippGrashoff** [comment]
I think I just messed up something to be honest. Everything seems to work at the moment. Merging the test surely wont hurt, but then this issue can be closed.

**Comment by romaninsh** [comment]
@abbadon1334 Can you PR that test you wrote? Then we can get rid of this.

In theory, the following two lines must give you equal response:

``` php
$model->get('name'); // or array notation
$model->getField('name')->get();
```

Also @DarkSide666 will make sure this is working.
