### ISSUE TITLE
Field type 'Email' doesn't work with addFields();

### ISSUE THREAD

**Issue by acicovic** [atk4/data#450]
When an 'Email' field type is added within addFields(), it is ignored. This might be a problem for other new fields as well but I haven't tested.

```
// Works
$model->addField('email', ['Email']);

// Doesn't work
$model->addFields([['email', ['Email']]]);
```

**Comment by romaninsh** [comment]
Suggested syntax:

```
$model->addFields(['email'=>['Email']); 
```

**Comment by DarkSide666** [comment]
This is a bit harder to change than I though.

Currently `addFields(['shipping_address' => 'address'])` or `addFields(['shipping_address' => ['address', 'caption' => 'Shipping address']])` syntax is used to define field alias in Reference classes.
In this case see 'address' in array - it's used as alias, so we can't use it as field class name too at the same time.
Will have to refactor this somehow, for example introduce 'alias' property in field seed
`ref->addFields(['private_email' => ['Email', 'alias' => 'email', 'caption' => 'Foo']])`
