### ISSUE TITLE
Field Email is relying on a missing function in Field

### ISSUE THREAD

**Issue by karakal** [atk4/data#472]
If you want to use Email the edit in the crud or somewhere else fails with the message:

`Error: Call to undefined function atk4\data\Field\idn_to_ascii() (in C:\tools\xampp\htdocs\fahrzeugakteadmin\vendor\atk4\data\src\Field\Email.php:98)`

And alas: There is no function idn_to_ascii() in Field.php

**Comment by DarkSide666** [comment]
`idn_to_ascii` is PHP function https://www.php.net/manual/en/function.idn-to-ascii.php

I think this issue is to old and no more relevant. Closing.
