### ISSUE TITLE
Sort order failing with exception on most non-plain fields. Model Persistence SQL

### ISSUE THREAD

**Issue by stokkeland** [atk4/data#473]
Consider this code (I tested on the ui demo data with a grid):

```
$model = new Country($db);
$model->setOrder('LENGTH(name)','DESC');
```

If throws and exception with Child Element not found - as it tries to run getElement on index 0 in \atk\data\Persistence_SQL::setLimitOrder()

In this function, if i replace 
```
$q->order($m->getElement($o[0]), $o[1]);
```
with
```
$q->order($o[0], $o[1]);
```
It works as intended.

To jog memories - here is a copy of the entire function:
```
    /**
     * Will set limit defined inside $m onto query $q.
     *
     * @param Model            $m
     * @param \atk4\dsql\Query $q
     */
    protected function setLimitOrder($m, $q)
    {
        if ($m->limit && ($m->limit[0] || $m->limit[1])) {
            if ($m->limit[0] === null) {
                // This is max number which is allowed in MySQL server.
                // But be aware, that PDO will downgrade this number even lower probably because
                // in LIMIT it expects numeric value and converts string (we set float values as PDO_PARAM_STR)
                // back to PDO_PARAM_INT which is goes back to max int value specific server can have.
                // On my Win10,64-bit it is 2147483647, on Travis server 9223372036854775807 etc.
                $m->limit[0] = '18446744073709551615';
            }
            $q->limit($m->limit[0], $m->limit[1]);
        }

        if ($m->order) {
            foreach ($m->order as $o) {

               // original
               // $q->order($m->getElement($o[0]), $o[1]);

               // Simple set order call - works in all scenarios i tested
               $q->order($o[0], $o[1]);
            }
        }
    }
```

Personally I do not understand why there is a getElement there at all - i do not see any reason for it.
Figured I would post this as an issue first - i can submit a PR on this one line change if there are no objections.

Now, there are additional quirkiness around sort order and data/dsql somewhere - I did not dig into all the details, i merely found a workaround. The below is with my "fix" in place from above:

All these Fail with exceptions:
```
$model->setOrder('COALESCE(ISO3,numcode,iso)','DESC');
/*  "If first argument is array, second argument must not be used"
    Something does not quite translate from a "proper" method call here
*/

$model->setOrder('COALESCE(ISO3,numcode,iso) DESC');
/*  "DSQL got Exception when executing this query" - Syntax error at end of COALESCE()
    query: "select `id`,`nicename` `name`,`name` `sys_name`,`iso`,`iso3`,`numcode`,`phonecode` from `country` order by COALESCE(ISO3, `numcode`, `iso)` DESC limit 0, 25"
    So it appears something in dsql is trying to intepret and enqoute columns perhaps, and seems to miss some items, and wronfully include the trailing ) on the last one. 
*/
```

So my workaround for this is to pre-enclose all my columns with backticks, and put in the first parameter only:
```
// Works Like a charm:
$model->setOrder('COALESCE(`ISO3`,`numcode`,`iso`) DESC');
```

I did not dig into where these parts are being worked out within data/dsql - my suggestion would be to stop any parsing/automagic on any sort order parameter that has anything [^a-Z0-9] and just use it as supplied...

**Comment by DarkSide666** [comment]
Well. I don't agree with this proposals for a fix. `Model->setOrder` works as expected - you can set order on particular model field, not expression. Removing `$m->getElement()` will always use value as string and you simple can't rely on field names hard-coded as strings. For example, what if you have multiple tables joined and require table alias? Or what if field is actually the expression?

Normally if you need to sort model by some expression, then you have to define this expression as model field by using `addExpression()` and then use field name in `setOrder()` method call.

I agree that sometimes this can be useless to define (and select) expression if you only want to sort data by it, but not actually select.
So I plan to come up with PR which will add support for this syntax:
`$m->setOrder($m->expr('COALESCE([iso3],[numcode],[iso]), 'DESC')`
This will:
- [ ] allow to sort by dsql expression without defining it as model field first
- [ ] allow to inject other fields inside this expression (see [fieldname] notation above)

**Comment by DarkSide666** [comment]
Implemented in https://github.com/atk4/data/pull/475

**Comment by stokkeland** [comment]
Okay fair enough - a workaround of creating fields is managable, and the ability use an expression in the setOrder is the fix, i didnt test it bu i assume it will work like a charm - thank you
