### ISSUE TITLE
Model addCondition with empty array value does not handle gracefully

### ISSUE THREAD

**Issue by georgehristov** [atk4/data#496]
When using `$model->addCondition('id', [])` the SQL select statement is created as `select * from table where id in ()` which causes SQL query to fail

**Comment by PhilippGrashoff** [comment]
oh yes stumbled across this already, too. Thanks for opening that issue!

**Comment by DarkSide666** [comment]
better fix here https://github.com/atk4/dsql/pull/165

**Comment by georgehristov** [comment]
Thank you @DarkSide666
