### ISSUE TITLE
reload_after_save: Inconsistent behaviour of Insert and Update

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/data#501]
Class Model: If a record is inserted, it is reloaded unless `reload_after_save` is false.
On Update: e.g. in Persistence/SQL, it is only reloaded when `reload_after_save` is true.

As the default value for `reload_after_save` is null, this leads to inconsistent reloading between inserting and updating.

```
//Model.php line 1860:
if ($this->reload_after_save !== false) {
```

```
Persistence/SQL line 958:
if ($m->reload_after_save === true && (!$st || $st->rowCount())) {
```

Both lines should use the same comparison for `reload_after_save`.

In general, I think its inconsistent calling the reload in Model on insert, but in Persistence on update. IMHO it both belongs to Model.

**Comment by PhilippGrashoff** [comment]
Just a thought to add here:
While persistence may know if there was some affected row, it definitely does not know if the model has a calculated field (without checking model). So there might be the case that Persistence thinks no reload is needed, but the model has a calculated field which would reload (who the hell knows whats in the calculated field function? maybe it changes even if field values stay the same?)

Thats why I think model knows when to reload_after_save, not persistence. How about something like that in Model:
```
public function reloadAfterSave():bool {
   //explicitely set to true or false
    if(is_bool($this->reload_after_save))) {
        return $this->reload_after_save;
    }
    //undetermined, if there are expressions or calculated fields, reload
    if($this->hasCalculatedFields() || $this->hasExpressions()) {
        return true;
    }
    return false;
}
```

That function could be used in places where at the moment the value of reload_after_save is checked, as in the two examples above

**Comment by romaninsh** [comment]
reloading on insert is mandatory to find out all the calculated values. it's on purpose.

**Comment by mvorisek** [comment]
@PhilippGrashoff is this inconsistency still present and can you propose a PR to fix it?

**Comment by mvorisek** [comment]
closing as no reaction, if you can reproduce, please post here a two examples of code, one where it works and one where id doesn't
