### ISSUE TITLE
Remove "legacy/1.0" branch

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#520]
Is it ok to remove "legacy/1.0" branch?

It seems like a leftover from history and it is a litte bit confusing with "legacy/v1".

**Comment by DarkSide666** [comment]
I think we definitely can delete this >4 years old branch, but - it's somehow protected and I can't delete it.
@romaninsh ???

**Comment by mvorisek** [comment]
Can be unprotected here:
![image](https://user-images.githubusercontent.com/2228672/76713389-a00c5a80-6720-11ea-859b-03fdc105586c.png)

**Comment by DarkSide666** [comment]
I wonder why it was made protected. Probably @romaninsh did that. We should better ask him I guess.

**Comment by romaninsh** [comment]
ok to nuke ;)

**Comment by DarkSide666** [comment]
Ouch, this was the branch on which SMBO relies :(
Stupid me ;(

**Comment by mvorisek** [comment]
@DarkSide666 I have opened this issue for `legacy/1.0` and @romaninsh probably deleted it with `legacy/v1 `.

If you want to make sure that you will restore the latest head, check Travis/GH actions. The CIs usually display the HEAD commit hash, so it should be possible to verify the HEAD hash. And then hope, that it can be pulled.

**Comment by DarkSide666** [comment]
branch restored

**Comment by mvorisek** [comment]
@DarkSide666 I noticed and protected it in settings yesterday.

**Comment by DarkSide666** [comment]
cool. thanks!
