### ISSUE TITLE
Fix hook trait usage

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#523]
Fix these once https://github.com/atk4/core/pull/133 is merged:

Regex:
```
(?<!  \$this)(?<!  \$m)->(?:onHook|hook)\s*\(
```

Code to be fixed:
- https://github.com/atk4/data/blob/42475e20f5f2ee66376ea062a7650d8c31412259/src/Model.php#L1387
  - return is indexed differently
- https://github.com/atk4/data/blob/42475e20f5f2ee66376ea062a7650d8c31412259/src/Model.php#L1611
  - return is indexed differently
- https://github.com/atk4/data/blob/42475e20f5f2ee66376ea062a7650d8c31412259/src/Model.php#L1649
  - return is indexed differently
- https://github.com/atk4/data/blob/42475e20f5f2ee66376ea062a7650d8c31412259/src/Model.php#L1690
  - return is indexed differently
- https://github.com/atk4/data/blob/42475e20f5f2ee66376ea062a7650d8c31412259/src/Model.php#L2112
  - return is indexed differently
  - is this to detect breaked hook or why is there an object check?

**Comment by mvorisek** [comment]
Please check the questions above and close if no actions are needed.

**Comment by romaninsh** [comment]
@mvorisek to answer your question - is_object check allow model substitution after loading:

https://github.com/atk4/data/pull/361/files#diff-83e9e6704bdede75a707d11294b67376R1035

**Comment by mvorisek** [comment]
> 
> 
> @mvorisek to answer your question - is_object check allow model substitution after loading:
> 
> https://github.com/atk4/data/pull/361/files#diff-83e9e6704bdede75a707d11294b67376R1035

@romaninsh When is it code intended to be reached? This code pattern seems to be used only here. See also my PR https://github.com/atk4/core/pull/187 which solves the hook break detection.

**Comment by mvorisek** [comment]
checked, probably no action is needed
