### ISSUE TITLE
Field value can not be unset (set to null) if field is not nullable

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#542]
Setting of null value should be probably always allowed.

Use case: https://github.com/atk4/ui/blob/92150346e6ab5e81150d15759a2e866be38ea510/src/FormField/Lookup.php#L435

![image](https://user-images.githubusercontent.com/2228672/78072386-54ec7b80-739f-11ea-9d06-75f65832a15d.png)

**Comment by DarkSide666** [comment]
I see, but NO. If field is not allowed to be `null`, then it's not allowed.

I understand that for this particular case for UI maybe it could be useful, but still I don't agree.
Most likely this has to be somehow fixed/changed/refactored in UI.
For example, by using something like `$this->field->model->unload()` or to unset particular field value back to default one you can use `unset($this->field)`.

**Comment by mvorisek** [comment]
@DarkSide666 Thank you for the feedback, closing this in favor of fixing the usage itself.

**Comment by mvorisek** [comment]
@DarkSide666 I still think that this is too strict - unset of a field should be allowed.

The typical use case is a link to an another model. If the linked model must be replaced for some reason, it makes sense to unset the link to it (ie. set it to null) and set the value later. This is fully supported by other ORM libraries.

What is the actual reason to not allow it? When new model is created/unloaded, the values are null anyway

**Comment by DarkSide666** [comment]
* imagine there is no UI at all - only data level;
* validation is done when field->set() value;
* we can't allow to set value===null if it's not allowed by field itself;
* model->unload() (also unset($field), but not sure about that) still sets field value===null.

So I think all should be fine.

**Comment by mvorisek** [comment]
Ok, we can not, under any circumstance, modify this behaviour as long as we instantly validate the exceptions from `set()`.

What about adding some method like `clearValue($field)` or `setNull($field)` to the `Model` class?

`unset` name can not be used, as it is used to clear the changes instead of setting the value to null, see:
https://github.com/atk4/data/blob/951fe84911bafbec85304217c927e2a7fec4adb8/src/Model.php#L1043-L1046
