### ISSUE TITLE
Remove VIM comment from files

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#546]
Many files start with comment like `// vim:ts=4:sw=4:et:fdm=marker:fdl=0`.

Can we remove it?

**Comment by DarkSide666** [comment]
@romaninsh added them time to time because of extensive use of VIM editor. I personally don't need them :)

**Comment by mvorisek** [comment]
Can be probably set globally in OS/user profile

**Comment by romaninsh** [comment]
😢 - they can go.
