### ISSUE TITLE
Make field names refactorable/hintable

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#547]
Is there currently any possibility how to refer to data with refactorability/hinting support?

If no, find a way to fix it.

It should work without the need of any generated stubs. Properties with some special phpdoc seems to be the best option.

**Comment by romaninsh** [comment]
Basically a challenge would be to avoid manual type-hinting here:

```
/** @var Field\Money **/
$num = $model->getField('amount');
$num instanceof Field\Money; 
```

**Comment by mvorisek** [comment]
This is not a solution, you can not type this in all places where you refer to any data field.

I am thinking about:
a) add dummy properties with simple phpdoc with the type like:
```
/**
 * @var int
 * @AtkField (can be also Join/Reference)
 */
```

and then some trait like `ModelWithPropsTrait` which will:
a) parse all phpdocs of all declared properties
b) compare if all declared model fields has properties and if all fields has documened properties (this we we can always ensure both in a sync)
c) the trait will unset the properties so PHP magic functions can work (they work only if the properties/methods are not presented)
d) map magic properties like ->xxx  to data['xx'] for unset/isset/set/get

I think this is extremely important for data. Not sure about the importance for the declarations (i.e. Field objects) - but we can use some magic with `->getField(fn() -> $model->field)` (only for PHP 7.4+).

**Comment by mvorisek** [comment]
Closing, probably too enterprise for atk4 community.

**Comment by mvorisek** [comment]
implemented in https://github.com/atk4/data/pull/800
