### ISSUE TITLE
"mandatory" and "required" field properties need to be refactored

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#576]
See https://github.com/atk4/data/pull/569#discussion_r414498175

Currently they are defined like:
- `mandatory` - prevent null
- `required` - prevent null and anything that evaluates with `empty()` to `true`

Currently there are two major issues:
- the names are not self explanatory
- two properties does not cover all use cases (we can not allow nullable non-empty field) and the values are not always valid (when `required` is set, `mandatory` can be false and can not be used for checking if the field can be `null` or not)
- the currently implementation does not even work like it is defined - see #575

I and @DarkSide666 propose to fix all these issues by refactoring this functionality to these fields:
- `notNull` - if true, field can not be set `null` or saved/exported when `null` is set by default
- `notEmpty` - if true, field can not be empty. Emptines should be evaluated to true when `(string)$v === ''` or for numerical types if `(float)$v === 0.0`.

With this proposal strings like ` ` (space) are considered non-empty. This is good to not solve multiple functionalities at once and it was so also originally as `empty(' ')` is evaluated to `false`. This should be fixed by normalization https://github.com/atk4/data/issues/577 which should be processed first.

These properties are very commonly used and therefore maximum care need to be provided to them.

**Comment by DarkSide666** [comment]
One thing to still think about is - should integer/float `0` be considered _empty value_ or not.
Empty string value do not carry any useful information, but zero euros is zero euros - it's useful information.

**Comment by mvorisek** [comment]
@DarkSide666 With numerical field `''` would have no effect as this value can not be persisted. So my proposal is to always allow zero ˙0˙ or values like `-0.0` in non-numerical fields.

**Comment by DarkSide666** [comment]
In non-numerical field of course. If `strlen(trim($value))>0` then it's useful information in my opinion.

**Comment by mvorisek** [comment]
> 
> 
> In non-numerical field of course. If `strlen(trim($value))>0` then it's useful information in my opinion.

Yes, but not all together, one reason why I opened https://github.com/atk4/data/issues/577 :)
