### ISSUE TITLE
Implement robust string normalization

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#577]
Fields should support these normalization options:
1. normalize `NL` (`\n`, `\r\n`, `\r` to `\n` - currently done always without option to set it on/off)
2. replace NL to space `' '`
3. replace all white chars (`\s` in regex except `NL`) to single space `' '`
4. remove all leading and trailing white chars
5. remove all trailing white chars in each string line
6. allow to exclude tabs (`\t`) from white chars

Used should have full control over all of these options and their combinations using one field property like `normalizeText`.

For non-binary fields all of these options except rule 2. and 6. should be on by default. In `atk4/ui` is makes sense to turn rule 2. and 6. on too for all fields except textarea.

Feedback and help with the implementation welcomed.

**Comment by DarkSide666** [comment]
Data normalization is in atk4/data scope, so we shouldn't be talking about UI here (textarea).
What matters is model field type (or Field subclass) which should take care of normalization (as it is now).
Also if you want to implement or customize field normalization, then you can always overwrite this field class method, but I agree that it would be good to make this configurable to some extent. Maybe allow developer to define callback method for normalization of particular model field?

**Comment by mvorisek** [comment]
@DarkSide666 All the rules above should be supported here so they can be easily setup for model fields.

**Comment by DarkSide666** [comment]
Field type `string` = one line of not-very-long text:
* should always do 1, 2, 4, 5;
* also probably 3 and 6 should always run because tabs or repeated spaces do not carry any useful information anyway.

Field type `text` = long text, probably multiline:
* should always do 1, 4, 5.
* 3 and 6 can be used for indentation, so these should be optional
* 2 should never be used with type `text` fields.

**Comment by mvorisek** [comment]
@DarkSide666 I agree plus

> 3 and 6 can be used for indentation, so these should be optional

indentation is more complicated:
- we may want rule 7 to replace all tabs with spaces (with (1-)4 spaces by default)
- leading white chars can be part of indentaion - so rule 4 and 5 must be defined differently

We may want also to normalize case (none, LC, UC, camel, pascal, snake). Just to keep in mind how to extend it in the future to prevent BC breaks, it does not need to be implemented immediatelly.

**Comment by DarkSide666** [comment]
You're right about 4 and 5.
4 is useful for type=string and 5 for type=text.

Please keep in mind that this is only framework. It can't solve 100% all possible use-cases. If developer needs something very specific then he can always extend class or add additional normalization. Framework should allow developer to do that easily, but not implement every possible case inside toolkit itself.
With that said - I don't think normalize case has anything to do with framework. Also replacing tabs to spaces is outside of framework scope. Framework should contain only these normalization rules which are used always or at least in 95% of cases and nothing more.

**Comment by mvorisek** [comment]
related feature request: https://github.com/atk4/data/issues/132

**Comment by mvorisek** [comment]
`string` and `text` types do already some "intuitive & logical" normalization
