### ISSUE TITLE
[proposal] - UserAction Modifier

### ISSUE THREAD

**Issue by ibelar** [atk4/data#588]
There should be a way for UI, or any other external action executor, to know how to react after an action has terminated execution. 

UI elements, on the other hand, may have to handle many actions, like in the grid component, for example, thus mixing action that required acting on the grid after execution can be challenging. We could look at the return value but this is not enough for setting up proper action executor in UI in particular.

Take the 'send_statementl' action in Invoice as an example. This action required to have the model be loaded but does not change any record values and return a string instead of the model, like add or delete actions does.

Since this particular action does not modify the value of the record, i.e. only send an email, it does not make sense to reload the grid after it's execution. Thus, a special executor needs to be created in UI, apart from other action executors, for not reloading the grid.

My proposal is to add a new property ($modifier)  to the Data\UserAction class that will tell executor of the action what effect it had on the record itself. This property can be defined as constant like the scope property is.

This modifier property possible value could be: 
- insert;   when records are added;
- delete;  when records are deleted;
- edit;     when record value has changed;
- none;  when records have not been changed

It would make the life of UI executor, or any external executor, a lot easier because we could react on the modifier value once the action has executed.

**Comment by mvorisek** [comment]
Are hooks not enough?

In UI, you should be able to add hooks for insert/delete/update and record what is needed...

**Comment by ibelar** [comment]
@mvorisek - I think it would be easier to set executor using a specific property in action. This way, you do not need to know what the action will do, but only what it did to the record after the execution and then respond appropriately in UI or any other external executor, like an API call for example.

**Comment by mvorisek** [comment]
> Since this particular action does not modify the value of the record, i.e. only send an email, it does not make sense to reload the grid after it's execution. Thus, a special executor needs to be created in UI, apart from other action executors, for not reloading the grid.

But usecase like this should be always solved with hooks.

**Comment by DarkSide666** [comment]
Probably can be solved by hooks, but this is quite common core case so I think that having such property is actually a good idea. It should not contain any rules for UI, just tell whatever executor is what action just did with the record. Then UI executor can decide should it reload something or not (atk4/data don't care about that anymore).
