### ISSUE TITLE
Email DB validation should trigger DNS validation only on new emails

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#614]
Emails should not be validated for DNS when loading from DB or storing back the same.

Maybe we can store like the first 20 bits (max. 1048576 values) of some hash and than check based on that. It is ok to misvalidate one email then send milion of requests due some import/exprt in db, and that should actually never fail except static/format validation.

**Comment by DarkSide666** [comment]
DNS check is disabled by default.

**Comment by mvorisek** [comment]
post here where and we can close

**Comment by DarkSide666** [comment]
Here https://github.com/atk4/data/blob/develop/src/Field/Email.php#L26

But probably it would be good to be able to validate "always" (on save, load, set like it is now if set to true) and new option - validate dns only on insert, for example.

**Comment by mvorisek** [comment]
I personally does not need it now, thus closing.

Yes, on insert will be good, but still non user input should probably not fail, thus I think the email validation should be triggered more by ui.
