### ISSUE TITLE
Renaming UserAction scope constants

### ISSUE THREAD

**Issue by georgehristov** [atk4/data#630]
Up for discussion/vote

I would propose for naming consistency and clarity BC renaming of `\atk4\data\UserAction\Generic` constants:

```
const SCOPE_NONE = 'none'; // e.g. add
const SCOPE_SINGLE = 'single'; // e.g. archive
const SCOPE_MULTIPLE = 'multiple'; // e.g. delete
const SCOPE_ALL = 'all'; // e.g. truncate
```

**Comment by mvorisek** [comment]
Previously:
```
    const NO_RECORDS = 'none'; // e.g. add
    const SINGLE_RECORD = 'single'; // e.g. archive
    const MULTIPLE_RECORDS = 'multiple'; // e.g. delete
    const ALL_RECORDS = 'all'; // e.g. truncate
```

no voting needed

but can we find better word than scope? - scope should be term for Model/Scope solely across whole atk

`FOR_NEW_RECORD`, `FOR_SINGLE_RECORD`, `FOR_MULTIPLE_RECORDS`, `FOR_ALL_RECORDS` seems good, but should a related key/name be named `for`?

**Comment by georgehristov** [comment]
Voting (or at least feedback) is always needed :)
In a sense `SCOPE` as prefix is appropriate as we are referring to a subset of records the user action applies to. Also in UserAction it is referred to as scope.
So keeping consistency is important.

```
$this->addAction('add', [
            'fields' => true,
            'modifier' => UserAction\Generic::MODIFIER_CREATE,
            'scope' => UserAction\Generic::SCOPE_NONE,
            ...
]);
```

**Comment by mvorisek** [comment]
And when I will want to restrict Action to a scope (ie. what property should I use)?
