### ISSUE TITLE
Migrate to Doctrine

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#641]
Why? / Positives
- well known and well tested
- fast incl. multiple level of caches
- incl. migrations/upgrade tools
- docs, driver support, well defined API, ...
- easy integration with other php projects (Symfony, Lavarel, Nette, ...)

Negatives:
- any?
- `data` claims to support other backends than SQL, but Doctrine seems that it support it as well - https://stackoverflow.com/questions/20555763/save-entities-to-a-rest-api-instead-of-db-using-doctrine-2 - so it should be possible thus not negative

How?
- we should be able to replace Connection with DBAL driver very quickly
- as Model is defines something like "virtual table" / "view", we need to support this for Doctrine, probably solved in Doctrine 3, see https://speakerdeck.com/dbrumann/what-to-expect-when-doctrine-3-comes-out?slide=23

What can we do now:

- [x] migrate to DBAL
- [x] add data mapper support to Model - ie. convert Model data to object/entity and add support for bidirectional mapping (load/save)
- [x] update ui code to use data from entities solely
- [ ] Migrate updates to Doctrine/DQL

later:

4. create some Model manager (for data mapper we need one Model for multiple entities)

![image](https://user-images.githubusercontent.com/2228672/86399188-1e2c4700-bca7-11ea-8160-5a1ab693e728.png)

**Comment by DarkSide666** [comment]
Maybe someday, but please not now. First get few 100% stable releases of all toolkit repos out.
Currently it's all to unstable to start something new and break what works already I think.

**Comment by mvorisek** [comment]
Do not worry, long term plan only.

Anyway, releases are waiting for you or @romaninsh.

**Comment by domainoverflow** [comment]
Please dont.

**Comment by mvorisek** [comment]
> 
> 
> Please dont.

please reasons
