### ISSUE TITLE
Scopes - support spaceship operator

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#661]
I think IS NULL is not needed:
![image](https://user-images.githubusercontent.com/2228672/88300445-c7dd8180-cd03-11ea-812c-fd4b1b7902c5.png)

However spaceship migh:
![image](https://user-images.githubusercontent.com/2228672/88300555-e5125000-cd03-11ea-9100-b27adadc84fa.png)
if we want not to transform every `=` to it (might have performance implications). The good new is, we can support it everywhere.

**Comment by DarkSide666** [comment]
That should also go into `atk4/dsql` probably.

**Comment by mvorisek** [comment]
I think one issue ticket is enough, but yes, needs to be implemented in dsql

**Comment by mvorisek** [comment]
I do not want to pursue this issue now
