### ISSUE TITLE
Drop Persistence\Array_ in favor of Sqlite in memory (full SQL) backend

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#699]
if benchmark of Sqlite with memory backend can show, that Sqlite in memory database is fast enought, I propose to drop array/hash table backend completely because:
- limited functionality vs Sql
- much easier repo maintanance
- [ ] sql table created from model

possible disadvantages:
- [ ] performance

/cc @DarkSide666 @georgehristov please provide feedback

**Comment by georgehristov** [comment]
I have implemented Sqlite and tested the performance and it is much slower compared to Array_ (something in the region of 10x).
But it can be useful in some cases like new values to model scope validation

**Comment by mvorisek** [comment]
10x may be fully ok, as we usually do not initialize with large arrays or calls milion times per request, the real performance difference might be almost unmeasureable, also, the difference may come from not optimally implemented DSQL

**Comment by PhilippGrashoff** [comment]
Hi,

I quite like Array persistence for writing simple tests. No setup of Sqlite is needed. If a DB setup is needed even for the simplest stuff, we might create a barrier for newbies. With Array Persistence, we could create some pseudo demos which run purely on PHP. And yes, everyone uses a real DB anyway, yet I find it handy.
Also, Array Persistence allows to easily add some persistence for model instances which should never be accidently saved into the real DB.

**Comment by mvorisek** [comment]
> I quite like Array persistence for writing simple tests. No setup of Sqlite is needed.

this will be the same, ie. no setup, only all SQL functionality :)

**Comment by PhilippGrashoff** [comment]
> > I quite like Array persistence for writing simple tests. No setup of Sqlite is needed.
> 
> this will be the same, ie. no setup, only all SQL functionality :)

So this means that every OS has SQLite preinstalled? didnt know about that.

**Comment by mvorisek** [comment]
yes, sqlite php extention is bundled with php and enabled almost everywhere - check your phpinfo :)

**Comment by DarkSide666** [comment]
My only objection is performance and it should be measured for bigger arrays too. For small ones performance probably will be close to equal.

**Comment by PhilippGrashoff** [comment]
What I also really like about Array_ is that you do not have to set up a table first, this can be pretty handy. I guess you'd have to do this first using sqlite::memory:?

**Comment by mvorisek** [comment]
> 
> 
> What I also really like about Array_ is that you do not have to set up a table first, this can be pretty handy. I guess you'd have to do this first using sqlite::memory:?

of course, this will be drop in impl, ie. table will be created by the `Array_` replacement

**Comment by PhilippGrashoff** [comment]
Ok, I want to test this :) Did a quick test replacing array with something I thought fitting, unfortunately it does not work. Any demo code available?
That was my quick try, just replacing Array_ Persistence:
```
        $model = new Person(Persistence::connect('sqlite::memory:', '', ''));
        $model->save();
```

**Comment by mvorisek** [comment]
not implemented yet, feel free to test/create DB usign https://github.com/atk4/schema first

**Comment by georgehristov** [comment]
I have working code for this, will try to allocate time later this week to publish

**Comment by PhilippGrashoff** [comment]
that would be great. Just stumbled across a limitation of Array_ in writing tests yesterday :)

**Comment by PhilippGrashoff** [comment]
wanted to share some simple code which does add the tables for defined models. Could be added to AtkPhpunit\Testcase:

```

class TestCase extends \atk4\core\AtkPhpunit\TestCase
{

    protected $sqlitePersistenceModels = [];

    protected function getSqliteTestPersistence(array $additionalClasses = []): Persistence
    {
        $allClasses = array_merge($this->sqlitePersistenceModels, $additionalClasses);
        $persistence = Persistence::connect('sqlite::memory:');
        foreach ($allClasses as $className) {
            $model = new $className($persistence);
            Migration::of($model)->drop()->create();
        }

        return $persistence;
    }
}
```

**Comment by mvorisek** [comment]
we need strict types first - https://github.com/atk4/data/pull/727

then we should use DBAL for migration (like https://github.com/doctrine/dbal/blob/2.11.x/tests/Doctrine/Tests/DBAL/Functional/Schema/MySqlSchemaManagerTest.php#L136 - we should generate DBAL Table / Columns from Model)

then benchmark/migrate to sqlite

**Comment by mvorisek** [comment]
closing as user can always choose sqlite :)
