### ISSUE TITLE
It is not possible to save anything anymore...

### ISSUE THREAD

**Issue by karakal** [atk4/data#815]
Out of nowhere the message "Model is loaded as an entity, ID can not be changed to a different one" is popping up.

 I just create a new Entity, set the values from a source entity and try to save it.

But the entity ends up in the database...

If I use entity->duplicate() as suggested in the documentation I just get the exception but no entity in the database.

I have the same function directly in my model definition, where it just works...

So what is wrong with this entityID and why did it get implemented in the first place?  And why is - as always - such a change, that is breaking behaviour that "just" worked never tested?

**Comment by PhilippGrashoff** [comment]
Hi,

check https://github.com/atk4/data/pull/801
This is the PR for fixing Model::duplicate()

**Comment by mvorisek** [comment]
fixed in #801
