### ISSUE TITLE
Atk/schema does not support table rename anymore

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#823]
This commit removed ability of renaming DB tables:
* https://github.com/atk4/data/commit/575641e99a1ae45ec95d4f9be574e28d58d7550e#diff-6e27f157ea7dcdc19af3d942e5ea48339b0809a6224f670dabf7de88070fb771L31
* https://github.com/atk4/data/commit/575641e99a1ae45ec95d4f9be574e28d58d7550e#diff-6e27f157ea7dcdc19af3d942e5ea48339b0809a6224f670dabf7de88070fb771L646

@mvorisek Any chance you could add back this functionality?

**Comment by DarkSide666** [comment]
Also doesn't support a lot of other functions like `importTable`, `createModel` and more which we had in `atk4/schema`

**Comment by mvorisek** [comment]
> @mvorisek Any chance you could add back this functionality?

no plans to do so now

**Comment by mvorisek** [comment]
Closing as this does not intent to impl. migrations.
