### ISSUE TITLE
DSQL - Support for JOINing a subquery?

### ISSUE THREAD

**Issue by scottfriebel** [atk4/data#876]
I can't find any examples of, or ways to write a query that joins sub-queries. Is this possible at this time? If so, is there any example of how I could implement it? I'm looking for something like:

```sql
SELECT 
    a.userid, order_data.num_orders, order_data.total_cost
FROM
    accounts a
        LEFT JOIN
    (SELECT 
        o.userid, COUNT(*) AS num_orders, SUM(o.cost) AS total_cost
    FROM
        orders o
    GROUP BY o.userid) order_data ON order_data.userid = a.userid
```

**Comment by mvorisek** [comment]
https://github.com/atk4/data/issues/183 is needed first

**Comment by mvorisek** [comment]
@scottfriebel please submit a PR
