### ISSUE TITLE
Plugins Architecture

### ISSUE THREAD

**Issue by Ayman-Nageeb** [atk4/data#885]
Hello, I need help

I am planning to build an extensible system (via plugins) using laravel

it for my project in the university ( I am a student )

the issue is that i don't know how to implement a plugins architecture in laravel

but you did it

i need to know how

so please give me any guide to start with

**Comment by mvorisek** [comment]
This is not a support forum. If you have a concrete problem/issue, please ask, otherwise use pages like stackoverflow.
