### ISSUE TITLE
Drop Field::serialize property

### ISSUE THREAD

**Issue by mvorisek** [atk4/data#893]
In favor of `ObjectType` - https://github.com/doctrine/dbal/blob/3.1.2/src/Types/ObjectType.php

type itself should be responsible for the typecast

**Comment by abbadon1334** [comment]
I like it and to make it no BC will not remove switches in typecast, so no pain no gain

**Comment by mvorisek** [comment]
implemented as part of https://github.com/atk4/data/pull/727
