### ISSUE TITLE
Create standard type set

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#90]
Types such as 'string', 'date', 'int' and 'boolean' (or bool) should be standart and all persistences should know how to deal with those types. 

 - [x] define list of types on a wiki page
 - [x] define normalisation rules and write documentation
 - [x] create test-script
 - [x] implement for SQL persistence
 - [ ] imlpement for Array persistence

https://github.com/atk4/data/wiki/Type-Normalization

**Comment by DarkSide666** [comment]
string = text, varchar,varchar2, char etc.
date = date, datetime
int = any numeric value, int, smallint, longint, float, numeric, ?timestamp?
boolean = bool, tinyint(1), int, enum etc.

**Comment by romaninsh** [comment]
This list can be useful too: http://php.net/manual/en/mongo.types.php

**Comment by DarkSide666** [comment]
so there can also be these types:
* array - array, list (mostly for NoSQL persistence)
* binary - BinaryData for NoSQL, BLOB for SQL

**Comment by romaninsh** [comment]
After thinking - the type conversion will be handled by Persistence SQL just when the data comes off the iterator before it's passed into $model->data

 - [ ] When query is being built also build a "transformation" consisting of [field=>fx, ..] array.
 - [ ] When results are fetched, pass them through transformator
 - [ ] Allow fields to define custom transformators

**Comment by romaninsh** [comment]
if we use "int" we should use "bool" btw.

**Comment by romaninsh** [comment]
definition of having a type - if field has a type then persistence will normalize it.

I suppose if we add 'array' into allowed typess, then MySQL will have to serialize it.

**Comment by romaninsh** [comment]
Fully fixed in #130
