### ISSUE TITLE
add support for normalization

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#94]
In most cases when user is trying to save " John Smith" he actually means "John Smith". It's just an accidental space, but that can cause trouble.

The same can be said for the numbers "394,283.03" and booleans "Y" / "N". 

The process of converting user-supplied values that are "almost good" into an actually good input is called Normalisation. Agile Data needs to have a well-defined way to handle normalization.

**Comment by romaninsh** [comment]
Other issues

 - saving empty string as null.
 - resolving related "ID" records and storing null if they are not loadable.
 - restricting length of strings
 - clipping min/max values of integers

**Comment by DarkSide666** [comment]
These are for Validator not Normalizer I guess:
* restricting length of strings
* clipping min/max values of integers

**Comment by romaninsh** [comment]
validator will produce error for the user. normalizer will silently clip things.

**Comment by romaninsh** [comment]
See also: https://github.com/romaninsh/validation#normalization-rule

**Comment by romaninsh** [comment]
https://framework.zend.com/manual/2.2/en/modules/zend.filter.html

**Comment by romaninsh** [comment]
#109 should resolve this.

**Comment by romaninsh** [comment]
More fixes in #130.
