### ISSUE TITLE
Create a standard way for specifying UI-related field properties

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#95]
When Agile Data is used in UI frameworks, then model definition will sometimes include UI properties. This is because Model and UI binding is often a seamless one-line process:

```
$grid->setModel(new Model_User($db));
```

and $grid needs to populate information based on model fields only. Here are a couple of things that UI framework will expect to be difined in the field:

 - caption
 - type
 - ui-specific options

```
$m->addField('birthdate', ['type'=>'date', 'ui'=>'DatePicker', 'caption'=>'Birth Date']);
```

We need a document explaining what is the standard way to implement UI properties.

**Comment by DarkSide666** [comment]
There can be more UI related properties like `hint`, `placeholder` etc. So `ui` property in fact could be  array with all these ui related properties.

**Comment by romaninsh** [comment]
yes of course.
