### ISSUE TITLE
Model->export starts id id= >0, but should start at id => 1

### ISSUE THREAD

**Issue by mkrecek234** [atk4/data#977]
With the current refactorings, the Atk4\Data\Persistence\Array_ will expect an id != 0.
This won't work, as the model->export function will start at id=0:

```
$xport = $vpmodel->export(['id','name','volume']);
$editmodel = new \Atk4\Data\Model(new \Atk4\Data\Persistence\Array_($xport));
```
Can we make ->export start with id = 1 then to make it consistent? In my case $vpmodel is a Persistent SQL model

**Comment by mvorisek** [comment]
see https://github.com/atk4/data/blob/8c9be7b490223d290de43958d4e538553a79f106/src/Model.php#L1688 and https://github.com/atk4/data/blob/8c9be7b490223d290de43958d4e538553a79f106/src/Model.php#L1754

that what is the 2nd param for, please confim it works

**Comment by mkrecek234** [comment]
@mvorisek Perfect, thank you for the hint! Working like charm

**Comment by mvorisek** [comment]
👍
